apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: gotway
  namespace: chartmuseum
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`charts.gotway.duckdns.org`)
      services:
        - kind: Service
          name: gotway-chartmuseum
          namespace: chartmuseum
          port: 8080
