apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: traefik
  namespace: kube-system
spec:
  encryptedData:
    # htpasswd -nb user password | openssl base64
    users: AgBZXQSH1kre6hAIeQLxt2QVKz58Tf6KLOWCO2KUREC9Cmf+hPVEeTvV85VUkAgR0cWCIn1gVDhelwknaBdSDvqNzVEmfdUBb85DzOLfZ7mlFLzjD6AnkiWRvzkIsCXzCGGOjmxjgyP0phyW/R3y8UOJsGUXI5cNNnhTqXhS6lwushmeKuTkojWB2xcW27ONIFmPl1GUMlLgKD9/MTvQdpVh5roChmdMtr9pD8o5kh04AQ99bruT8pIHm0LjiCn3kZX7zbrXfzWRJ/KUK/A8lVEIywVSeMj7Dw4PxMqH8XiZhtdpNFeiO45dxb6ovQMJEuu0PQM3zrrqEMkg7akpP/5iuaWo30ZNFyh3/oN7e3fLOGTmDGGbKOkjWfR4BY7G4mlUrEdKszEtcNDIvueysWgC86XD/yWs5S1/78LFn6EinhCiaGeUb2Odj4gMPeCAmabQLFj513AlB3mVqmogpTJGh6/+higyCGwIdPzeoifv/JNixnhGllHJW2imRvw4KrgUX6ir8VexfxMlgT1b8mU7yI/MRbPF2dWjWL7Fvv9CHS25ys9K3y+uPwLz0do2qciAirpH73ef2kLpph9qJDXPv1iCLvoYExObTdAffynpS+9mIKtohbgGoAAVFh1EDBEW1HB279SHtseW/LMx0qz3uSMmZefKzbdC0ZT1mVBZq1HZG52Aksr++B7fXhJLkATCgRRvhcNzg96rCIxOeGmRVeWnH0HCvg2NJyGEaUCH2j+DR1229NSbkvk2kzCh8A==
