apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: traefik
  namespace: kube-system
spec:
  encryptedData:
    users: AgAtK05nkNSF8957iJGDSkKswKfldYsWfn20JNBhPG4B3mfW0rkG+rwHyAEVfh2tTeFTKALXW9WD6qjIvd5z3qGWDBwRI6rSe81ZdqJ1oxRp1HikY9UKk9hvnek8YPhrIqMoM6a/f8KU0GZq2Iw8tuuh07J7ZyhDI7cEl1IC0l1adLn7Js89KWRKw7ac6OVIAaRqMuIBadlTF/4YSJp41SfY5v1EV221kU3V2iTsl2lUeSlLsEUlAuGwWmz1qAcHwn6jYmP9LQsksngiF5OdZP/Kyf00/z+OhdXLOHhCWOWIxUe7sDltnoYM7eiKVXe+OKrBye3GeeCa7e4Wi7IiyL7c1FsXSCNJmRHIDZezJdfxdwJrt/b0usdYsWSUSaSWJyG38aWmx/YdIk/b2r8qTLgop0TKHcFa4ORUCWFleItZxbEksEWxD7GSTDyO2edse+UaPYjs26lsIm3l1foksOysE4bx2vdWHFN6pW+hd9PQVkcFX6gEU5Ctv3XGH9YMsHEUSxsF242WEhxZZLtJW2OgPMX6u6h74TqJYHGRqJKq48MhgQgFPCG+g/XP54+3EGptw9jqPR1puOy6gAYAii/lsrDmz1fddFZoR8F1G+wTLjNPDaw2F7pK+3sBtJBXFRQ2qdyOmCqpTAqktE9bgRFKrVOhgEwfdP/AMFw6S5nWJL9fersE6BkaUGghRY0RjZi3kFTK80gra9p9Esh8JfithgLXGsnZb7ZUhDI5g0zRM0bFc+IYi6ps21pBMrM=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: traefik
      namespace: kube-system

