apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: rook-crds
  namespace: flux-system
spec:
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/rook/rook-crds
  prune: true
  timeout: 5m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: rook
  namespace: flux-system
spec:
  dependsOn:
    - name: rook-crds
    - name: prometheus-crds
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/rook
  prune: true
  timeout: 5m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: rook-ceph-cluster
  namespace: flux-system
spec:
  dependsOn:
    - name: rook
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/rook/rook-ceph-cluster
  prune: true
  timeout: 5m
# ---
# apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
# kind: Kustomization
# metadata:
#   name: synology-csi
#   namespace: flux-system
# spec:
#   interval: 5m
#   sourceRef:
#     kind: GitRepository
#     name: flux-system
#   path: ./infrastructure/synology-csi
#   prune: true
#   timeout: 5m
# ---