apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: iot
  namespace: flux-system
spec:
  dependsOn:
    - name: rbac
    - name: sources
    - name: gateway-api
    - name: sealed-secrets
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: ./tenants/iot
  prune: true
  timeout: 5m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: media
  namespace: flux-system
spec:
  dependsOn:
    - name: rbac
    - name: sources
    - name: gateway-api
    - name: sealed-secrets
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: ./tenants/media
  prune: true
  timeout: 5m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: github-explorer
  namespace: flux-system
spec:
  dependsOn:
    - name: rbac
    - name: sources
    - name: gateway-api
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: ./tenants/github-explorer
  prune: true
  timeout: 5m