---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: client-info
  namespace: storage
spec:
  encryptedData:
    client-info.yaml: AgBnSWXalEJTFtEQMuHYKsZxGiDDyMtRazCXoQJx9pGZEiIchOE5XAy8B9aqgfbGl75jna4b/pueNBKCdHYFg8TLbb6HeHUpufcRW9Se5LZD4vVC7XEH5do8qCx47yck64TTEFES9Lxr/YP9gPxr11Rwwl5cKLF/GBDGKDwLlHvm16cC/Yy9wpeErsdJLLsCABI18JeMzpxwf3orQ8So/MiMqq9nC//h8PG2pgqzkAESZfjrEn8t8/+9bwAX2sotdfT31b9J7d8gJv1FXiRTLi9ekX4kpAHDiKxlAR9SB+PFwIIc9pbsLyTF/+lH9Z9rEWWcxU8u65FHbLvFpBgEd6ckcb1QI1Pa6IcVBL07rlBBvvSqwwvpWHPhBWsQvpwJ90aB2m43etUL01O8RDsyPNPBy9FfiaQK0D2NCPW1w1Bq/auDsxh2J3PhR8OmzPVEWgY8IsybLN7RkkcNIyCwk2eeD93MJiNSzKc/7dkcPfF7d39eLNMPv4HPzkdd/ZzF9QCzQ+oHJeBFXT7IbpLUZ/uLNwIF3hmFbRVWM+hH5V2/QD8bmU1g+XSUOWoZO/c/74AuVC7iuhNKdkVuDpYy0iTAoXddo+sYlYwz3FAr1TXxq3TuntWMMzMXNTdwghSzFeOv3dgpBW5nvZhULXsChae10OaMQBK/skyUnqnHh56Za84oL0pjx5/M8EdeszeJ2+IouPi0y1berAj8nxhLhJqNSH13lql2Qnq48n8g/fUAaXHWu3nGPrxewj9A9nrPm1ZDE7DUiSzDNMjktOwLRakcGCSA0xhnJCbBzKM80O16E5M1mKqqjVKC3EAFWKFNIvgm4U6lQDdg6+3XKk04b9fiUWBKXGMLLA==
  template:
    metadata:
      creationTimestamp: null
      name: client-info
      namespace: storage
