apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: gotway
spec:
  releaseName: gotway
  targetNamespace: gotway
  chart:
    spec:
      chart: ./charts/tenant
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  interval: 5m
  values:
    repo:
      url: ssh://git@github.com/gotway/k8s-gotway
      branch: kubernetes-1.25
      path: ./clusters/production
      secretName: flux-system
