apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: gotway
spec:
  releaseName: gotway
  targetNamespace: gotway
  chart:
    spec:
      chart: tenant
      sourceRef:
        kind: HelmRepository
        name: mmontes
        namespace: flux-system
      version: "0.1.0"
  interval: 5m
  values:
    repo:
      url: ssh://git@github.com/gotway/k8s-gotway
      branch: main
      path: ./clusters/production
      secretName: flux-system
