# apiVersion: v1
# kind: Namespace
# metadata:
#   name: dns
# ---
apiVersion: v1
kind: Namespace
metadata:
  name: pki
---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  annotations:
    volsync.backube/privileged-movers: "true"
---
apiVersion: v1
kind: Namespace
metadata:
  name: storage
  labels:
    topolvm.io/webhook: ignore
---
apiVersion: v1
kind: Namespace
metadata:
  name: database
