apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: storage
resources:
  # - data-pvc-snapshot.yaml
  - data-pvc-provisioned.yaml
  - minio-config-sealedsecret.yaml
  - minio-scrapeconfig.yaml
  - minio-sealedsecret.yaml
  - minio-snapshotschedule.yaml
  - minio-tenant-helmrelease.yaml
  - minio-tls-certificate.yaml