apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: minio
spec:
  jobName: minio
  scrapeInterval: 1m
  staticConfigs:
    - targets:
        - "minio.storage.svc.cluster.local:80"
  metricsPath: /minio/v2/metrics/cluster
  scheme: HTTP