---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: minio
  namespace: storage
spec:
  encryptedData:
    CONSOLE_ACCESS_KEY: AgAlboU9YXwxv7EL+yf446s3XoFPZBso+Z5y41SFi57g92n1mlb9cXueiSpYSH4ZqD9v9D+jf4DZQlo2VGrx4ahrMnWBXk4w+E8gQ+asK2LMd9iCRYfalbGiHQN+Adg/XjM/TcJHDy6j5/A6hUZYUhstKzu1Wr9J2RE9aS6JGY4GHVbeuvSbqAHV4WFtYp8CPQW2uY9GkYJ602Ov6xlLyE27wbwRvd2s5kJFyDX3gQMgfYfTyc0o/ZaveVyelifxN1U0HZ+7N1E6munkp+GYfv1EzuTGtsoMfj1lDPac1LaIE3gFtglBjOcuedw07wCH9ZuUAsckmDf+G2cxSAAySE+4+WRTKTPRnsKo2AXzenku+Jps5XHlgbvfLc/k78GDCRNK6AKkzhPNCkuF1DGHVfZU83rn3Yg1yow8+9thXxI5pVi5QwfSBKECSfMLgbxO3BTjAD//JZg3+n/xJ/hZwYGHfB/6pDqOn6nlYJ3WyyGt/xigU//EWGLGhHj0W8HyOIkvBH6sBUg3k1IE7xaCpODtyRtVWfY15BMgYapGqg0EI/hAXFgadi06zRUjXe6J9C0nx2VNKSynFeyy2HPzen4s+VhWM0IyETfWk7i45kDIgeZN9NBWD2L+9pCkir6LUnQU+JIOxcNlPbfn6zDSvwTYEAe99uetcY9Ap0wXZ9qFQm0lquckMOGrjDWmk6oE7rhAFwIBqg==
    CONSOLE_SECRET_KEY: AgBvhyRmOb+ro9SCFnPFl1xB/rU+3tBhUxmNmas3pLw/gKTqfU1r7sdLFWocACQO2+o0AjRHlwqDnFXtSfi8Q8H6dgd87c2yfx+m9vbPTb0EXibAThFCte3ri8vh+DTOQZdT4vASLNBXS+eHUyOodeaOPlgqnFIFazCP3vVRdOcewnqmVw6GBJh992iTi+Dgp3xoIdpTVoVq/91EEzIKY++HvaK3KszXQ6LiWkEzytFdawChrF1YieE9zKsujnhgzeFyOVYurGOUWGhRQwzolzX2HeGNm98yykKdLEDiR0RIjJrOONVX7ScAUi3B8C+PPDdYCffega2mK/vv3jgVRqwLw+iWvm5S4dEB2Y1at+zcnvifUWYXp2wc/nB6j2ObdoVHiNQgqf2ze7VOYfwm0Ovb+qAzfTnz6AEQUBFZXjKF9CqkyPc96pyuapoLjkc/xTaDuOyFlibvl+rErqV9D6HrI60iqOYZ5ow46YDYmljLzp3SLi5g59x6Ax35V3/wrHLsaCKT31fdoaCID2N7a+svMXp/fF2ZK84BSu5DvKWh0UEC5coEI/e7qmeeExqXxK2NQZwK4Ncdm8IIclNCeb0Dn17a0eIdF/oNBY9yZRi5Qj1PMqtw4r8bVXNW+l56rqJqtNAOzH2tMuy4WGydQR8IByYLo37OEVt0/j/iVBXOnQr1ZtFM+dql+BbIXB5KWtp5dJHfMG8u9RBwg74/lIfUnM/juA==
  template:
    metadata:
      creationTimestamp: null
      name: minio
      namespace: storage
