---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: minio-config
  namespace: storage
spec:
  encryptedData:
    config.env: AgCuC/CPTnU0eeWXGk9us+XaLDXOD8A8msplkunAqD512OUx/RMQ8dFQmVr9f1//fsdwsIB6GMjDiJZ4PvIf9+GsZdCG5IbhD9VpVt3uZcITbtBDhuvdrGyqCyeRyKx6PVWIg3IvCsrNhHylkk8AOhF1/3gJieo6WNJapTJIGr/7vdFxke89NV0x51qQXOsAW0KCoAYJ2kRBsdxU1goZZ1LCsa6Ltnq4CCs20VXqQCUJsrZSGjq3he38DDnsWRu1ks+JFoou9Eu2oY3S0Fv9S2Gzj6YXu0VWnAiFACVzw1JrJIh75tiOQmRlaqCXNXCd2gK64OMTvqEd12nLzioDF3mxnHNsfzERoKTWTasyHx3QoLcj7uSGq6eSEshJfFbUAU+ECV0vHRmAumHjkZXoJndKGgFbWx7n2PUs+AMhe+Bb3Zha7jv8cLFWF6f8sQfgp8JM85ERb8ndrHXWDHr/LeubAe23MdBEcVn0vA7LJkeeGl2plvzTrh64fKrprcv6fXbyc/ycBKF4FyIIMqa0WGMAf9MJtWeHumekv31Vxp3DDKT5eZAKzraPn3Br5fRzXZ2nZp6V8r06jC8FJtrU/OQ/Vkj7CzuUgyin0TX51mYvzP+3QWAtpJugwDMU2m+9JQL0K2XwyocB1dMVXBvswOUhVUG1hz5K0uy/ivxcZvXmhJa+k0NRw+C9PIOO6JUkJO/+3JFHDhUthqPZ0+NzSM5tnIuBnYsdv7G1y7RpkBWNK33/qFkcRZ7FQHAoeYrRXciXPjo6kwhgpA+VtdQlT53Xh49tSLnMxRcxBB8TdG/qjf/PAz30Gi6t61PLXSkYVF+MkmHGkZQ6N8db2jR5U0sIp7+3axk=
  template:
    metadata:
      creationTimestamp: null
      name: minio-config
      namespace: storage
