---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: minio-config
  namespace: storage
spec:
  encryptedData:
    config.env: AgByuBI542ui978PIp4UwBPKOynmYBmE9KrVZMxH0xeIXE/mKLFs6CYD+BAAq2rJNGR4S2dRSekkD1gd3c2PIU6Clqb1csYD6Wpo55DLzXu47J7U0RRSjFgbYmnRGIV9Xjpp7T9hEbNy2K43PO0Uv1dLCv3I1XFMBLQ9kqsinhETMajhYvaBmmyFAtNMsnNLCIcv0TaBrYKS/6mWnKJFoFXSdJZQgKx9TYEYeLSOFieK8yt9i+4CHcVf4vMaZ0xZvFX+4xuSOg72xM8l0v0mmrp5aG91IF5HWUsbDZCON8IGPi3FD58d1Yax5wgCYHpzCzxwpvbahPvNB0C1mSb5r/Uty15xdI6lvYisMqvfOiIEJDhYfes00DVCn7ztyiTbt7C4sbTcQhQS0Vy4+FgaQpj8eVn5xY6bzTxKSrJclA0nh5vKKdG6mLxB/tOtqZCt+2K+C3SRPGrCMGrnyrPPcev6KX0CCz3jo99Ur+QOZZXK5SJGg0MMZb97W8HmioxCHFajjWqefHnCOGK7yJvMM7hX+c6gEc2i5JRUn9LxoOblNooJq8qUh+a4JtCxAT6lRiiZS0JH9aAz3MBJiiLDeW9BQchTjTonEUgPL9OSKtBT4+EqL63xtbXQxEUpfO7UwSn5yntC1f3+aNQH1pKcaCNnfDAKB/kFvL2P0SotwOtoDIPq2YPCDWE+EbU1+98ygK8E2pHYgOGSlfg6ciutbfkpt458g2LJAgasDv9IjhAb23qh3z1gZ/XBQdgWBfc+/0E7giHSem3JZiFPtSYK1peAYHkJ77YBGEo5I1IUxLR83n/JQ0rlQRYIoxyR/dfAoJbaKwYD1Spnq6ZnuEEX35VHp6mLV7TGRdHyKFXnAF54s1jkw7XvZEX+ZO/U2PIw1kBjNQZ/uDfJpJ3kuRwMGGUkKvy+H0fMSZbcO48=
  template:
    metadata:
      creationTimestamp: null
      name: minio-config
      namespace: storage
