---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: minio-config
  namespace: storage
spec:
  encryptedData:
    config.env: AgB5hHLmr+RQ5hDEZYBGykwvyLK8e7cBoJQlVu+yUEhpe2TDlodOKKWorqbfNXag2cDFZ9gOElXL09Ct+sEZgCxGvv900LyiWDVc35m0Ui5mIF7RikODnZGI7FIAqTOR2WiUPWn+isBj1zVrSGCxb8LOK6CVVGg6KHXGQslKhLPFYow4k4FkAiq1dfZc2kGfG0rEjquEdbBo69Y1td3eo17eY6BKy6FTNvv22jMiwT+SjOAUMR/qf651bbQZougbF1/Ks0aATIjfCwI19fAb3Ja4ghZ6RU88aNZCCdNXZc69AwgMJ9+nJjw1Owe7d3TFQkYYAzd4ONO/BaDaFEhGwm3+vdgywHQYJTL3wEzdntr1deVGBs0yNJ/xzux2zoEBaE/3C/zoPjOkUxcGsJ/09QRJdwotikIbWVKVUYgAY/zxpo4zIdCjdSzPC0f2j//JtaLeuF7qgrKkj2O1FelYrMGYt6hS6kfxadpQRvg34SiJsr9rO/b8lgX0HW1CKJPsP340SJ79JjXUZyCKT0hxgiw9jq+a382qy/4LPP6nLBEZFP36RhGgW5NzqIcJitLECEEP7jW8RIJKIUJiZAdF+BXH/Virb/EEmdDEIY24J/G7d7z2UViCQY5IzEi1TfwCSONo4G+h1Sw5almx9/YbQomnqyaia5tGbIqf+wZsjteiux++3sg8M5YD0JB7+yR9VwWXPKYxbew267zr49GukGWakHuBSbxc3HqYtcQa6jLRBf+hdhEPLrLNl5uaok2yPtL7mdMzFyEXeYo8TmOJ7YQf3UqrckhB+l1OSBj+nTIanK/SitDL1FthHb4oE+5zpa64OfIDQwOwAV8hoJw=
  template:
    metadata:
      creationTimestamp: null
      name: minio-config
      namespace: storage
