---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: minio-config
  namespace: storage
spec:
  encryptedData:
    config.env: AgBkKXeB7UcL1rNMECuqdkLUiWAvvbxIluo7tsJL5QjJv1EGkgb5vVq5Y0lq5CaqyQxBtVT8xwZRtroB5qk9D7MkAv/Wvg3NqXz+nPJwh15kruyBYjWV2EB9ce5I4L39dO41T9HCp6GA0cCUML7YtXfnfmbyGQs+8DBXPWYVV0VSH8uJJyhkLpXMEf3PmrvzzlbxePZvwsXnuD9asKQoi786ROIom5I5mm9ymYscgTBu9IXJUyAlowjbMKeGs1IWUEor+eTvtpkG24k4U+rfD5sTHZqpyyus9OojW36ZGx9sha+XAqMboONVRRpnCLwuVnUssYYbzTU6B1innSx91IYL3AIbV6TGmfnZ8yxuHEMBdw0uABhTNZMLzPSFdX56rMvrcn87gJFBoCRjWCQZV3U4ADQAJNWPHGtBV+KWQvmjsf3z9yDS4nPGtoxtLbFZusKRE7LRgkdwVvBPAOKDqg2nyTP0Q96pZ7TDTer8x317Ss0/WxIrLPV71rhO2lHpyaS2gddiZNxuU7tjCQ6qe+LXDNa9XYZx54BxWSwKDMLBImbDn8LjnrlQnHrx4HzIvNF1tvqXI4efVp89sMLdr9CtcSpA+HimbChWeZ9n91qh5Yc6rEPQKIGb6Sjn17cEEkmewwkmKI1QAuTzuifXbaHd0Urfkza0LwWNZ5xhnh76r/KWX1jvvYwQmSoyKyNaBO0Ld6AlqGRPJnpSgNmYPHCz3c+Ojbh5FQPEMWMeow/qgMh3Gu8x9TQWbdMtHN7Bmn+wUb4IwnmYzKUlQQJD/rSu8MyHiGjbTnbeSfSs
  template:
    metadata:
      creationTimestamp: null
      name: minio-config
      namespace: storage
