---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: minio-config
  namespace: storage
spec:
  encryptedData:
    config.env: AgAFaHtP2CBz9i0P5mqUHkMDKer2F9C33lDKoouqY+oaU61djYFqRGhWxJaWUGhDsnlGOIvVgjYMtjSdruACEFz+M8xhr6rEgft9dm6bt0cllTQYtdaxaKSLSiX8cttdXWPaMl+e2k/TAEhsb1qjNWCtSxDTyxOyHhoswlsCTodPAxnsVGCchp0WAEAx0zm+pnQWtMCXH10QiSqS4aErjw0mOx98vO8n75eJ59zqkU9crjSWVyip3I7KXjrzCdhpiSkJ0qyU3m/T9owwM4y8a+ftrhyHBVQOym2HVd75zwsZR75LoCz7Kv/xQ0AYdSb9wpR47VK+pULThfRtLHj2MYIb9/UTpCJZKgx1u7AJdK0QNgMEGhc11GXmCpq4EyqG6A40EWpB62hSWyiN1ZlxtNOJwLZIrkHCVPhhOgW2JBnKJTFtysmpIIhrWrDrbx7VKvg3MR5+HKQhE+n9gMnzBnaumrhKkIFHquPGw03ijC1fZFOEyiAfTLcQgPeU1RNK6kN/X6kNpisupOz+nPNKIx6k2f5mFrN0RUkiqsltLpZtxBCylO7UZbQlH/Nt/6Aca05r/yRc6Wn8Ow3dguRK/m5oaveG2POfo+k0lkVmk/hYKwbVluPtGfd253G+B40m8N4zl38XaCOkMApFsvQxvrbnDJUDkPiD2XtCqW0q81AzkrPIgd/ltykQSoc5TzrxAdnTBy2W8MgjiEbEdVM81aF855sS5fbSxx2vfDGypaOwl3DAWFiekP8VuowWRtHa53WOR/yQ3FB4vyCZYH1J
  template:
    metadata:
      creationTimestamp: null
      name: minio-config
      namespace: storage
