apiVersion: snapscheduler.backube/v1
kind: SnapshotSchedule
metadata:
  name: seaweedfs
spec:
  claimSelector:
    matchLabels:
      app.kubernetes.io/name: seaweedfs
      app.kubernetes.io/component: volume
  disabled: false
  retention:
    expires: "168h" # 1 week
    maxCount: 7
  schedule: "0 3 * * *"
  snapshotTemplate:
    snapshotClassName: synology