apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nfs-provisioner
spec:
  chart:
    spec:
      chart: nfs-subdir-external-provisioner
      sourceRef:
        kind: HelmRepository
        name: nfs-provisioner
      version: "4.0.16"
  interval: 1h0m0s
  values:
    nfs:
      server: 192.168.0.120
      path: /volume1/kubernetes
      volumeName: nfs
      reclaimPolicy: Retain
    storageClass:
      create: true
      defaultClass: false
      name: nfs
      allowVolumeExpansion: true
      reclaimPolicy: Delete
      archiveOnDelete: true
      accessModes: ReadWriteOnce
