apiVersion: tailscale.com/v1alpha1
kind: ProxyClass
metadata:
  name: compute
spec:
  statefulSet:
    pod:
      nodeSelector:
        node.mmontes.io/type: compute
      tailscaleContainer:
        resources:
          requests:
            cpu: 300m
            memory: 300m
          limits:
            memory: 2Gi