apiVersion: tailscale.com/v1alpha1
kind: ProxyClass
metadata:
  name: compute-small
spec:
  statefulSet:
    pod:
      nodeSelector:
        node.mmontes.io/type: compute-small
      tailscaleContainer:
        env:
          - name: TS_EXTRA_ARGS 
            value: --accept-routes
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            memory: 512Mi