apiVersion: tailscale.com/v1alpha1
kind: ProxyClass
metadata:
  name: compute-small
spec:
  tailscale:
    acceptRoutes: true
  statefulSet:
    pod:
      nodeSelector:
        node.mmontes.io/type: compute-small
      tailscaleContainer:
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            memory: 512Mi