apiVersion: tailscale.com/v1alpha1
kind: ProxyClass
metadata:
  name: compute-large
spec:
  tailscale:
    acceptRoutes: true
  statefulSet:
    pod:
      tolerations:
        - effect: NoSchedule
          key: node.mmontes.io/type
          value: compute-large
      nodeSelector:
        node.mmontes.io/type: compute-large
      tailscaleContainer:
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            memory: 512Mi