apiVersion: tailscale.com/v1alpha1
kind: Connector
metadata:
  name: controlplane
spec:
  hostname: controlplane
  proxyClass: controlplane
  subnetRouter:
    advertiseRoutes:
      - "10.0.0.0/24"
  exitNode: true