apiVersion: tailscale.com/v1alpha1
kind: ProxyClass
metadata:
  name: controlplane
spec:
  statefulSet:
    pod:
      labels:
        "networking.mmontes.io/managed-by": "tailscale"
      nodeSelector:
        node-role.kubernetes.io/control-plane: ""
      tolerations:
        - effect: NoSchedule
          key: node-role.kubernetes.io/control-plane
      tailscaleContainer:
        resources:
          requests:
            cpu: 300m
            memory: 300m
          limits:
            memory: 2Gi