apiVersion: tailscale.com/v1alpha1
kind: ProxyClass
metadata:
  name: controlplane
spec:
  statefulSet:
    pod:
      nodeSelector:
        node-role.kubernetes.io/control-plane: ""
      tolerations:
        - effect: NoSchedule
          key: node-role.kubernetes.io/control-plane
      tailscaleContainer:
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            memory: 512Mi
