apiVersion: tailscale.com/v1alpha1
kind: Connector
metadata:
  name: control-plane
spec:
  hostname: control-plane
  proxyClass: control-plane
  subnetRouter:
    advertiseRoutes:
      - "10.0.0.0/24"
  exitNode: true