apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cloudnative-pg
spec:
  chartRef:
    kind: OCIRepository
    name: cloudnative-pg
  interval: 1h0m0s
  values:
    config:
      clusterWide: true
    monitoring:
      podMonitorEnabled: true
      grafanaDashboard:
        create: true
        namespace: monitoring
        labels:
          grafana_dashboard: "1"
