apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: database
resources:
  - barman-cloud-helmrelease.yaml
  - barman-cloud-ocirepository.yaml
  - cloudnative-pg-helmrelease.yaml
  - cloudnative-pg-ocirepository.yaml
