---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mariadb
  namespace: database
spec:
  encryptedData:
    password: AgAxgIukojJNmzDxAryjnOtTt4SQHKNFrot7xsALYPzSr5zYri6G5ymrKdfaLQCG/Ld0+lR4DR6fgr3HGYFpf9DvH9D4e34+y+JPvlmhaLVVF3T439YHthEDOq4a3pQ1PHidPfE57e+CxXygufCYn61tjTVqOPYc5m/AqDIeTuvw0RZetKpkbJM9oFopHQMWjF1jb4uEMLSTbOCMKYmX2/RD4XG/css+7UqI0iSZzqXk/tabGaOhM0O095lCZF9AS+tVhSb05K4OCSpLoNGSxt2azK1WZXaoCAquq27OcNPTjfBK8OmyZqO1yWLL1c9DEUCKMNwFa6wQ7U/wPnI1Gd77HnO29uUBcO3lhFhgb+t8gIHazUs7hd61bDFxf94dFDSa1pbxtZcSxTrtDqkdt+zZox1VesBe5lFyIHXB3Fe+byvrAHqITyIf6IPbLlsGXmTFPwiOrYQBcgg96xnRnPJHdmDDVOGFVx/kjrcuz4p2tvACgt1BFyAVuySYGfnxySuOMHRuqnxeS0hyvAsG2VHdE01OjQI7ZCSj34x/OuWKxsSchGgGOZROdxH7O/L2Z/3+1W8pm8C7lG6pu1cVQ+69GFFn3zu1HrjvxDMl8Jw7DK+ENM/jbP88Xok+pDWaMr8U2WiSRNWCZNPACS1smpGuaa099zn2mTvvyyMeiulo/bUOsYErk1OfqWWz4OceZdc5IeQ7uFDkJ1j3
    seaweedfs: AgAuQvVDcdQxcXozL+S5thBJEutasdX2SECBtMPSGQ/5TdtAjl6QhkJQHzMpALL/cq2I0GPuaqhf43/05KfWPB+6agSOjautYL7JiVb7gEP6WuqnxF8KElwxpk2XRDkdc8dgDVa1edKBcPJ9dgu+ce6aNnGso+45ILINfMCHaGNilBvaASEwGE8L5Mdd7VEpkmlJPDPYHb8JP80QTXRD8XTKBy1R0aKF/58oWrpj2ltDQtT07Vg09mCiPDUSgHFRdAJOQlI+Z/asIzVlemQzfZWFY6QiwQchBn44dSSDRw/xnbc+F83q/74Q/IXdLPS+zt8gk8B89OkawERCbt4uapvVk7P30l2OnVIJgxrn1bC+vEYh0it+SRNewbt8QIX9kMNfSAkkJDzhmtHV9cwtVW18LSmgxi0+IyqAEzQRy2yffCnjIdbysIflDLehc2p3rsD/2Dpjr7uN9KKnd1dyx/0n1pYeWaR6oGgRFTV62aOT5swFm3v6wlgrdHvHPwiFJWftN/Zz7e0Es1ZeCGnI1mBqWnplmqen3o7nTvvULmqdXc/MeWtSId7uZk9gdy+5sLbd3N0RzVOEGA/oS6jHpNgmYIelVI7TLqAhhr7FVY0ugePRQKpfLrW8nVpSQWwcICchd8xnEr7z1NJPRZyqrEGSEFkNTnMJNf1RQZ48bhs3txB7eDNG6Tpjeh/9lUJpQ5DaHJPcHoUSXXET4qQ=
  template:
    metadata:
      name: mariadb
      namespace: database
    type: Opaque
