---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: client-info
  namespace: storage
spec:
  encryptedData:
    client-info.yaml: AgABDbNSc7PE+R42KCAIliREi4WIvn3PuyuWr+7tyV0pAgR92GSNZORIqObm9h4lDyRC2AOvgrXPWR51GXFBitzZDLQxRC1mRD3X/CUYLpJtGdsRZnmErEkGKSgRyXX63tMrPIUNVJI8sETVyRaWbheeXjI6ga88B1sGViyLnuSgCiEJPmmzNCkku4px4kgew3HOvjhZLnitqp+K+ssKtFeWJGUmphis6ciXFSYwsfxDLpSec8XcSVhUIosfcxDbm0hoy0mZb0sOis7S+3aDaM1PBPjClFvsoz+xhyN8kH+bFj80sfdUpu7EXL/cseK0Llqx992rGiO6za8HhbWDP9AhTpwCZRpgyXFVKXDHG+piLputoDCG5suLWNvjIadXVisl39YPaBQT7r2egFEHXMZPxEG64h9p6zBBED3cwFIBtMs/qqTOeVW9c2LLoeW6GsUldzPUesrF+XF3fHH4Qj/UCurGR/xc6XvMIfmNVe5zxUgCEcMkdCgQTUjjk207oq3t/Xvnl4sulCtLMGeqXKxYGXz1ANMtcs/qZgWxdGnTw+CxtnXT7vg1Rq1nNVBBnL0ahhiQWOc+3VKx8q+X8QaXezhH5FZcUyDgXs+O9yfR/54hR5XlIgAdW5tUtZjKd44vaUfXcvdstiwZDZhPdi06zlf1x/r1I4JHI2hFjK3lMU6iAQGT0nW4fuRKVo0oiIXX+8FSsDUNJRYpRb7SmMvOHyT3Juag1L5jKlkVG+HCCPVUqSw08bgGYLc5d9jMss7hqdXAxXndxtcy145YjzXx4iuWGQGxjcw/vkGe2XP6V3Y1h418mQ4LLkCWE3Cr05efk6QrRIvPi0eyd43zHZUIEswoycCUdCbLiVG6ZR8z
  template:
    metadata:
      creationTimestamp: null
      name: client-info
      namespace: storage
