apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: csi-driver-nfs
spec:
  chart:
    spec:
      chart: csi-driver-nfs
      sourceRef:
        kind: HelmRepository
        name: csi-driver-nfs
      version: "v4.9.0"
  interval: 1h0m0s
  values:
    driver:
      name: nfs.csi.k8s.io
      mountPermissions: 0

    feature:
      enableFSGroupPolicy: true
      enableInlineVolume: false
      propagateHostMountOptions: false

    node:
      tolerations: []

    storageClass:
      create: true
      name: csi-nfs
      parameters:
        server: 10.0.0.50
        share: /volume1/kubernetes/csi-driver-nfs
        mountPermissions: "0"
      reclaimPolicy: Delete
      volumeBindingMode: Immediate