apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nvidia-dcgm-exporter
spec:
  chart:
    spec:
      chart: dcgm-exporter
      sourceRef:
        kind: HelmRepository
        name: nvidia-dcgm-exporter
      version: "4.7.1"
  interval: 1h0m0s
  values:
    serviceMonitor:
      enabled: true
      relabelings:
        - sourceLabels:
            - job
          targetLabel: instance
          action: Replace
    runtimeClassName: nvidia
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: nvidia.com/gpu.present
              operator: Exists
    tolerations:
    - key: nvidia.com/gpu
      operator: Exists
      effect: NoSchedule
    - key: node.mmontes.io/type
      value: compute-xlarge
      effect: NoSchedule
    resources:
      requests:
        memory: 256Mi
      limits:
        memory: 1Gi
        nvidia.com/gpu: 1