nameOverride: ""
fullnameOverride: ""

image:
  repository: mmontes11/helm
  pullPolicy: IfNotPresent
  tag: "3.8.1-alpine3.15.4"

jobSpec:
  backoffLimit: 5
  parallelism: 1
  completions: 1

chartmuseumUrl: http://chartmuseum:8080

chartsRepository:
  url: https://github.com/charts/charts.git
  branch: main
  path: charts
  command: make release

usernameSecretKeyRef:
  name: secret
  key: username

passwordSecretKeyRef:
  name: secret
  key: password

nodeSelector:
  {}
  # node.mmontes.io/type: compute

resources:
  {}
  # requests:
  #   cpu: 50m
  #   memory: 100Mi
  # limits:
  #   cpu: 100m
  #   memory: 200Mi
