apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: sealed-secrets
spec:
  releaseName: sealed-secrets-controller
  chart:
    spec:
      chart: sealed-secrets
      sourceRef:
        kind: HelmRepository
        name: sealed-secrets
      version: "2.18.6"
  interval: 1h0m0s
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  values:
    secretName: sealed-secrets-key
