apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metrics-server
spec:
  chart:
    spec:
      chart: metrics-server
      sourceRef:
        kind: HelmRepository
        name: metrics-server
      version: "3.8.2"
  interval: 1h0m0s
  values:
    # TODO: add operator to auto approve kubelet CSRs
    # See: https://github.com/mmontes11/k8s-bootstrap/issues/2
    args:
      - --kubelet-insecure-tls
