apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metallb
spec:
  chart:
    spec:
      chart: metallb
      sourceRef:
        kind: HelmRepository
        name: metallb
      version: "0.13.7"
  interval: 1h0m0s
  values:
    prometheus:
      rbacPrometheus: true
      serviceAccount: metallb
      namespace: networking
      serviceMonitor:
        enabled: true
        controller:
          additionalLabels:
            release: kube-prometheus-stack
        speaker:
          additionalLabels:
            release: kube-prometheus-stack
