apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metallb
spec:
  chart:
    spec:
      chart: metallb
      sourceRef:
        kind: HelmRepository
        name: metallb
      version: "0.14.9"
  interval: 1h0m0s
  values:
    speaker:
      priorityClassName: system-node-critical
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          memory: 512Mi
      # TODO: remove after finishing migration to homelab-v2
      tolerations:
        - effect: NoSchedule
          key: node.mmontes.io/type
          value: compute-large
        - effect: NoSchedule
          key: node.mmontes.io/type
          value: compute-xlarge
    prometheus:
      rbacPrometheus: true
      serviceAccount: metallb
      namespace: networking
      serviceMonitor:
        enabled: true
