apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: flux
spec:
  groups:
    - name: flux
      rules:
        - alert: FluxResourceNotReady
          expr: gotk_resource_info{ready="False"} == 1
          for: 15m
          labels:
            severity: warning
          annotations:
            summary: "Flux resource {{ $labels.customresource_kind }}/{{ $labels.name }} is not ready in {{ $labels.exported_namespace }}"
            description: "The Flux resource {{ $labels.customresource_kind }}/{{ $labels.name }} in namespace {{ $labels.exported_namespace }} has been in a non-ready state for more than 15 minutes (group: {{ $labels.customresource_group }}, version: {{ $labels.customresource_version }})."
