apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: flux
spec:
  groups:
    - name: flux
      rules:
        - alert: FluxResourceNotReady
          expr: gotk_resource_info{ready="False"} == 1
          for: 15m
          labels:
            severity: warning
          annotations:
            summary: "{{ $labels.customresource_kind }} not ready (name={{ $labels.name }}, namespace={{ $labels.namespace }})"
            description: |
              "Flux {{ $labels.customresource_kind }} resource has a not Ready condition (name={{ $labels.name }}, namespace={{ $labels.namespace }})."
