apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: network
spec:
  groups:
    - name: network
      rules:
        - alert: InstanceUnreachable
          expr: probe_success == 0
          for: 2m
          labels:
            severity: critical
          annotations:
            summary: "Instance {{ $labels.instance }} is unreachable"
            description: "The instance {{ $labels.instance }} has been unreachable for at least 2 minutes."