apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: alertmanager-telegram
  namespace: monitoring
  labels:
    release: infrastructure-prometheus
    alertmanagerConfig: telegram
spec:
  route:
    groupBy:
      - alertname
      - job
      - namespace
    groupWait: 30s
    groupInterval: 5m
    repeatInterval: 12h
    receiver: telegram
    routes:
      - receiver: telegram
        matchers:
          - name: severity
            matchType: "=~"
            value: "warning|critical"
  receivers:
    - name: telegram
      telegramConfigs:
        - botToken:
            name: alertmanager-telegram
            key: token
          chatID: 565598
          parseMode: MarkdownV2
          disableNotification: false
          sendResolved: true
