---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: alertmanager-telegram
  namespace: iot
spec:
  encryptedData:
    token: AgBC31RBMJJFg4KkXiqbgIjPAD5H3QvnMFY5R/Ayt8cwuq85KMc6E1pY17wRJUU8fMAKWrqdgKN0xwQIVSjwA25nWbdVkIHJNtWzk/AbVSF8oGOVtM+nuUUC7QSepheFRQPzRz5bDwPH6NqD1TAnmbCKboYNFnIGjoV6WSUb0VVOmjqbwTTCinsuQprY/1O0EAJbJWJjASUMH8VudrQE19VzEkqI151jnKYYeNOOfeahtX0SQYVLy42G8DGrpgnwYxAMa++Xga25JGMxTSfQO3kR8QKoRv//S2RS9yMMy/F0pno13fb/KWyQGSJCkcn+vylROKeKnbu/Ddz4GiVhqBvyJc8rlDOUxcnRDcRYIu/782QAI9sUQYBSOVSnH1tY6ZhbzuClzCtnL4Yj3rIIpXocoH00CmOvrecd6RJFUlO54x8RERQMeDDmd7CG6z9MtDoXzvBAm8tz3PnQ7YIbud0U19W3rtwAGwCCoPtcH8a5CJMFJNWl7RK637Ty6Ul+df4XZmbbFInPngWno/8/ueIN5evVxJk0nZ5ftp3u8HJkbJhJKYMZ1jmTSJTmxdKuHRbmW95rnSp3vyFnDb2XZXVl2bE0CS9P280hbYr2V50Pd3TGM+wqKCyuOzN4v8KtAelLk6vWKV3NA9Hvr/27GpBexW/IR/vTdFgMiwbzGzJVp8roqJpeeFw7i2bMloqjxB4PV5GzmtnPYkHbNea0LffF7xAEcInD8zj/G3FEXTwsoK6S3bSPbUpn6HnwBKZr
  template:
    metadata:
      creationTimestamp: null
      name: alertmanager-telegram
      namespace: iot
