apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: blackbox-exporter
spec:
  releaseName: blackbox-exporter
  chart:
    spec:
      chart: prometheus-blackbox-exporter
      sourceRef:
        kind: HelmRepository
        name: prometheus
      version: "9.3.0"
  interval: 1h0m0s
  values:
    fullnameOverride: blackbox-exporter
    securityContext:
      runAsUser: 1000
      capabilities:
        add: ["NET_RAW"]
        drop: []
    config:
      modules:
        icmp:
          prober: icmp
          timeout: 5s
          icmp:
            preferred_ip_protocol: ip4
            ip_protocol_fallback: false