apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: prometheus-blackbox-exporter
spec:
  interval: 5m
  url: oci://ghcr.io/prometheus-community/charts/prometheus-blackbox-exporter
  ref:
    tag: "9.3.0"
