apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
  - alertmanager-httproute.yaml
  - blackbox-exporter-helmrelease.yaml
  - blackbox-exporter-ocirepository.yaml
  - grafana-httproute.yaml
  - grafana-sealedsecret.yaml
  - kube-prometheus-stack-helmrelease.yaml
  - kube-prometheus-stack-ocirepository.yaml
  - prometheus-helmrepository.yaml
  - prometheus-httproute.yaml
configMapGenerator:
  - name: flux-kube-state-metrics-config
    files:
      - flux-kube-state-metrics-config.yaml
    options:
      labels:
        app.kubernetes.io/part-of: flux
        app.kubernetes.io/component: monitoring
configurations:
  - kustomizeconfig.yaml