apiVersion: volsync.backube/v1alpha1
kind: ReplicationDestination
metadata:
  name: prometheus
spec:
  trigger:
    # schedule: "0 4 * * *"
    manual: prometheus-3
  restic:
    repository: restic-prometheus
    destinationPVC: data-prometheus-kube-prometheus-stack-prometheus-0
    copyMethod: Snapshot
    moverResources:
      requests:
        cpu: 1
        memory: 300Mi
      limits:
        memory: 4Gi
    moverAffinity:
      podAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchLabels:
                app.kubernetes.io/name: prometheus
                app.kubernetes.io/instance: kube-prometheus-stack-prometheus
            topologyKey: kubernetes.io/hostname
    cacheCapacity: 10Gi
    cacheAccessModes:
      - ReadWriteOnce
    customCA:
      secretName: homelab-bundle
      key: ca.crt
