apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: prometheus
spec:
  sourcePVC: data-prometheus-kube-prometheus-stack-prometheus-0
  trigger:
    # schedule: "0 2 * * *"
    schedule: "*/5 * * * *"
    # manual: prometheus-4
  restic:
    repository: restic-prometheus
    retain:
      daily: 7
    pruneIntervalDays: 14
    unlock: prometheus-1
    copyMethod: Clone
    moverResources:
      requests:
        cpu: 1
        memory: 300Mi
      limits:
        memory: 4Gi
    cacheCapacity: 10Gi
    cacheAccessModes:
      - ReadWriteOnce
    customCA:
      secretName: homelab-bundle
      key: ca.crt
