apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: default-tls
spec:
  dnsNames:
    - "mmontes.duckdns.org"
    - "*.mmontes.duckdns.org"
    - "*.internal.mmontes.duckdns.org"
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: letsencrypt-staging
  secretName: default-tls
  usages:
    - digital signature
    - key encipherment
