apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: traefik-external
spec:
  chart:
    spec:
      chart: traefik
      sourceRef:
        kind: HelmRepository
        name: traefik
      version: "28.3.0"
  interval: 1h0m0s
  values:
    instanceLabelOverride: traefik-external
    logs:
      general:
        level: INFO
      access:
        enabled: true
    ingressRoute:
      dashboard:
        enabled: false
    ingressClass:
      enabled: true
      isDefaultClass: false
    ports:
      web:
        redirectTo:
          port: websecure
          priority: 10
    providers:
      kubernetesCRD:
        enabled: true
        ingressClass: traefik-external
      kubernetesIngress:
        enabled: true
        ingressClass: traefik-external
    additionalArguments:
      - "--serverstransport.insecureskipverify"
      - "--experimental.kubernetesgateway"
      - "--providers.kubernetesgateway"
      - "--providers.kubernetesgateway.labelselector=gatewayclass.mmontes.io/type=traefik-external"
    service:
      annotations:
        metallb.universe.tf/loadBalancerIPs: 10.0.0.80
    deployment:
      enabled: true
      kind: Deployment
      replicas: 3
    affinity:
     podAntiAffinity:
       requiredDuringSchedulingIgnoredDuringExecution:
         - labelSelector:
             matchLabels:
               app.kubernetes.io/name: traefik
               app.kubernetes.io/instance: traefik-external
           topologyKey: kubernetes.io/hostname
    podDisruptionBudget:
      enabled: true
      minAvailable: 1
    resources:
      requests:
        cpu: "300m"
        memory: "300Mi"
      limits:
        memory: "300Mi"
