apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: traefik-external
spec:
  chart:
    spec:
      chart: traefik
      sourceRef:
        kind: HelmRepository
        name: traefik
      version: "20.8.0"
  interval: 1h0m0s
  values:
    logs:
      general:
        level: INFO
      access:
        enabled: true
    ingressClass:
      enabled: true
      isDefaultClass: false
    additionalArguments:
      - "--serverstransport.insecureskipverify"
      - "--experimental.kubernetesgateway"
      - "--providers.kubernetesgateway"
      - "--providers.kubernetesgateway.labelselector=gatewayclass.mmontes.io/type=traefik-external"
    service:
      annotations:
        metallb.universe.tf/loadBalancerIPs: 192.168.0.90
    persistence:
      enabled: true
