apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: traefik-external
  labels:
    gatewayclass.mmontes.io/type: traefik-external
spec:
  controllerName: traefik.io/gateway-controller
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: traefik-external
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
spec:
  gatewayClassName: traefik-external
  listeners:
    - name: websecure
      port: 8443
      protocol: HTTPS
      hostname: "*.mmontes.duckdns.org"
      allowedRoutes:
        namespaces:
          from: All
      tls:
        mode: Terminate
        certificateRefs:
          - name: websecure-external-tls
            kind: Secret
            group: core
