apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: traefik
spec:
  chart:
    spec:
      chart: traefik
      sourceRef:
        kind: HelmRepository
        name: traefik
      version: "20.5.3"
  interval: 1h0m0s
  values:
    logs:
      general:
        level: INFO
      access:
        enabled: true
    experimental:
      kubernetesGateway:
        enabled: true
        gateway:
          enabled: false
    additionalArguments:
      - "--serverstransport.insecureskipverify"
    service:
      annotations:
        metallb.universe.tf/loadBalancerIPs: 192.168.0.90
    persistence:
      enabled: true
