apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: traefik
spec:
  chart:
    spec:
      chart: traefik
      sourceRef:
        kind: HelmRepository
        name: traefik
      version: "10.15.0"
  interval: 1h0m0s
  valuesFrom:
    - kind: ConfigMap
      name: traefik
