apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system
resources:
  - helmrepository.yaml
  - helmrelease.yaml
  - sealedsecret.yaml
configMapGenerator:
  - name: traefik-config
    files:
      - values.yaml=values.yaml
configurations:
  - kustomizeconfig.yaml
