apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: networking
resources:
  - external-gateway.yaml
  - external-helmrelease.yaml
  - internal-gateway.yaml
  - internal-helmrelease.yaml
  - traefik-ocirepository.yaml
