---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: seaweedfs-admin
  namespace: storage
spec:
  encryptedData:
    adminPassword: AgBDeVixAmVSgX7pC0gaESiQlXTAiDSbcEsiIK3i+bKO0j6fOAJWlsE+yw7J+Xfbnclhv/lgobbsBeD1dM4wyWC+MxBlX3K8KpjYHEeqrqr4HZowmBO6Ii7V1WeK6IezqSEJ6zxIAKrAulP59rFXOOFd1TMjWEyjAALB5Czi0w6gRln04h0OZj5e+vD9YjR4IGYKnXvleXIDtIZyjbvz13sj37ANAKPdvJCnLMSzqjGtJAAfirJEliGO8XMD8GyIz+OcRHZeWnSsanljdU5zQwSkycpgMWPGHHTh7EFAOAbb8M0INo7Jl+0E2F4WQo+PI94MdmhIMr3t11pfOuqpLp0aCA/3Z0GpAsEYm/vD17gQAO7XhkyRtpZgh6mCbB72XxG+ZSU7q6JOQTon9x6ZQJCw4iV+zsDVAP67rHrKt9WNtQ031pP/DltolSo7/fwEyXF7OvKodqBMIiJ+ADw/0zB3elut6kPq/DX9dVsLGjgWerv5rd57xK23DEvR2IC1/w6g4ZnkhlEeV/YYmTXFafAJLej1JKU4bc2e7h7q4r9cF48r6rxdjFK8segFfLjzSqfCd/IjKG4ntEWSKfM2WjXEQTgrbZdf/aQATWf3JOJW38DA6qe6hFBB2pLcC8TNT/Hp7UF6QA0dWrEJn5QwrnW1xWYjfsQWdt2+KaO6X1us/NRZGkLAfOg5DGW8Y9cVuopmRXhcLSfAnEcjnPiVuikskhE2sg==
    adminUser: AgCAKweDXvbXwdrHca0W7/8YSOT1TPgxoZVGC/k43Ii+1fYQoi8dBvElll3dOtuWGVT1qsz/5eahhnPVpHVzoDz/MS1LR21RplzL5xVd43nHg56PWpfNy87GwG7OKt0Mc6pn/Yfk4ldTQ3795clLEaHsyNHgo865+K46lNw/Ck2vWeDf9zD49qBzB6g1O40z+H5WnNpNs34GB3F7zG7jndMEKSAjoVjn//mdNWI7ikO1Tbb+jiJAgGpygZ/9t1JYcS4LbkOpDBig/RVX2hBrrr9sluOCgwYZ4wEgeKtNf6SFIyNXivLljvTR08EVZoXEAObNqAf5s9Vl3oPeSQ2gn/PhAPEuoCSdeo7d3PLqLqP7JlYAMhYR9aAxZlrayFJxqq3+Z8MQ9RdKMOPUQV7n16gtaNzkPLK3emZWFz2W3qwazLosaFsg9DNROEG5NQmDBvTv4vP7Cd7aFiGQie6dwJaLhW7s1OGdcNWfTu534gLRJSM/8JS9ijq2yn0OCVPZ7xPkVzEP2Jb2HGY+Rotv/53rq0OFF+WKzyrwxz7hC6vKaeauJkYoT9wewqvtbyGkdGhVMUEGNhU4Qov3AqEAfzqWOwZIRTbEwwp0+MeyWEqLATPXFkulszB1RRqnG9B0tSvnyTpNOnRwVbQqb4RBn1l3JK2gV6XUj/cqTV923lVCHMjaJOC+r4UQGI2WBO6rw6VAOLsq2Q==
  template:
    metadata:
      name: seaweedfs-admin
      namespace: storage
    type: Opaque
