---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: seaweedfs-s3-config
  namespace: storage
spec:
  encryptedData:
    seaweedfs_s3_config.json: AgCWW3amZnhJ+2xk11wKocXUfD47ZoE6dLcipXl0+89HVdLPkTgKf5FA616OzfOR5aiWqHxmQ0DZd+cx/JVIE/pz/HdeCd+CpwOVuQe+O1ymwhcBeOMj1UFkhplyIJ+upluILxLoRBmANc2L4AuUD6bpavh5v0x9ziRnIMe6/B47oM+WXGXsgOeUXdgdHrUqc/z5vmPuA2lDYOIH2LFHhHkXT7bK+IRGmROrVRu1KvjMQ+fXEAU7sdBicXXtUS0FEn7NhY+817vHgidcVw1d/S6J9taRTrFV4NeMh0zW1oaoip/UcYPdRs+dc+vruXcvtIeejD08E8pdTkB+CEjs1LvgLI8o2MRSgPJ1gymxOij++NQOdbui66XIlfNLG6Udkez/vpjDOqzP9XwwEhVKbWZAERiwKLDQfFarWzQvwK/e6DQROlCoEsskFn6eAWm0FO0ZF1m2HOHCmfQPhzDMPgHusqpThVK6Kka+WNz1JiMNxApdJq3OtPYAv320Uxf1Oq7FTdEO1n11H0MV6toMTbU1mOW4muS9jh9Hayxk0rL6Hr5IO9rV8leMU/1wyN8Nvtdc2yXGigyOSgbsUyZdbIanBfJxmm3VtOrC8Xi3zCgVMsCrFVRj9FrYM6aqfcabpT/axXzD9vkYQHt4wu3bwAe+Zl4icfToY6n8ZGLsXG7lVEwPP+nIKNjjgvpOYMFFoy7wN7Zc1H3pG7dvI17jAxbWgodo9Ft65nVOA+pyS2cC5S8tSJGJ+I6DyXNSpAz7W7HZ5osKDd2PSJ4iCpXHB6gSWn2NnOb1cKLuN2QDm/7qTmyinJHLwdoszyxzBlLUoHsh064OS2INHJC53d3QIZS0MQPgrBybHY5ms02j9WYqWztSDYOXK71tiyrYc4xBBcyqXszSJnKrK8ZWesS9xzEuNJnP0SeLPnb2M4JxhedFfbxAbUwNdMV/h/rR/cIGTjkN4JcXmCgofbCTmC2VaTM5veAzBHHkKBbeKm7QmfWmyDoBdczhl2JGsAz47p4QHjtQ6QkTfymV0T4zPiUABq5O8vVUTkf0rzcTaWQL9t76ImlNZTnqJmUTYFjQemJklEu6AaUspA==
  template:
    metadata:
      name: seaweedfs-s3-config
      namespace: storage
    type: Opaque
