apiVersion: batch/v1
kind: CronJob
metadata:
  name: chartmuseum-init-sync
spec:
  concurrencyPolicy: Forbid
  schedule: 0 0 * * *
  jobTemplate:
    spec:
      backoffLimit: 5
      completions: 1
      parallelism: 1
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - args:
                - git clone https://github.com/mmontes11/charts.git -b main; cd charts;
                  make release;
              command:
                - /bin/sh
                - -c
              env:
                - name: HELM_REPO_USERNAME
                  valueFrom:
                    secretKeyRef:
                      key: BASIC_AUTH_USER
                      name: chartmuseum-auth
                - name: HELM_REPO_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      key: BASIC_AUTH_PASS
                      name: chartmuseum-auth
                - name: HELM_REPO_URL
                  value: http://chartmuseum.registry.svc.cluster.local:8080
              image: mmontes11/helm:3.8.1-alpine3.15.4
              imagePullPolicy: IfNotPresent
              name: init-charts
              resources:
                limits:
                  cpu: "1"
                  memory: 700Mi
                requests:
                  cpu: 200m
                  memory: 200Mi
