apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: database
resources:
  - redis-operator-helmrelease.yaml
  - redis-operator-helmrepository.yaml
  - redis-operator-metrics-service.yaml
  - redis-operator-servicemonitor.yaml
  - redis-operator-servicemonitor.yaml
