apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: redis-operator
spec:
  namespaceSelector:
    matchNames:
      - database
  selector:
    matchLabels:
      name: redis-operator-metrics 
  endpoints:
    - port: metrics
      interval: 30s
      path: /metrics
