apiVersion: v1
kind: Service
metadata:
  name: redis-operator-metrics
  labels:
    name: redis-operator-metrics  
spec:
  ports:
    - name: metrics
      port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    name: redis-operator
