apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: traefik-external-basicauth
  namespace: networking
spec:
  encryptedData:
    users: AgANupIQq3TQq9zXKAPfmgxzeWCnMDlwDPXxhWmGwI/jRQwnCqhZOeojdtqVtTjJp/scU2rhwGWBFPxRCzoEAOFRG6mXT8TUxnPWzE1MEBXoWXa0iHqHxedv1opWMOLPTuZXWpBBPgX/t5CcUbWxSLZjR9LNqYlBvw8pQ9P2kMIV0zJ4zCdPrEpg5slSTEOQlKDisyNR7u0asYqiEfcB9gnAaWqG6n0tMZg2oStgBUb/zRcFZL0/PzvQ+9k1Q7R3mvdpWeXG1SxwsZqkmAI4QnS2g2aeyjjNnzEWFOGN7E6ji9IhpQ33+NxqRlW7pUnKycaWKGYIb2Dnf73iTAtG9VEaAaZewQkQ3pnCjkwu5I7iFt7NR0CbkRuCADQvOrRvX+k5GFlHF1FTMtFpy8j5su/5MsuuqW1SPdgRyaNcUU66t5sW45h3DYsrv2AUAtn4yHoNKlMvK+IJUk0anpd5lgrsw2vJsOUlsIt/h13/uoGjH3hXFLvQHOd4TFYckjh+PhK6jkD2u1wAg23PP4YPlpdeEm5d4l2eR/lwFztU1IMGTaWJDJgnXI3nZ5QXIF3A+bqhJ86LT3jDn0jsEwunn4FND2OShHGauhqbO0ayilKNR+t15OnmdeZBf0tXlLzhBdULcJJMj3mSKN3KmbcFZf/aZDWDihCOmQjhnWqB69w0xjNZwTi9OgowASGjB+3KNMeAqx4Te9Zl8Azy7a2etLvhxoGP82uPi6R20szemdIX7kDiZe2PK5IAaHJCQ2nOTr6MSJZpRxWS5j+UvoE=
  template:
    metadata:
      creationTimestamp: null
      name: traefik-external-basicauth
      namespace: networking
