apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: traefik
  namespace: networking
spec:
  encryptedData:
    users: AgBVPafBEDgCZbFxmZiUbSQs3fjeM8BLbiSjnf8mFi/sy+PbwRiyGmbkfmyYcg/Lg51dCvp03wauDz5RntMaenp6w0budvtYlJsh/0Fz5ZQiYUzRr4QS9cKJKU9LTVvWgpN2o2gzr4EksJIEYYnutEVkyS050Mj9I19Sdfdce92AUhOuVI50fdOSCMf6s34NEF6BRiypfvrQ5r/BWU7JcZVsFi64+f9kkSwv9Gwm6sd6+jw/36kZGUdC8VQxiYHVfYQtw45hD4C8CEWWthEZtaZc2a8f0og3/0DFE2lk7A6E94T+GYjCtDXytoG49riEJExdNFWdBpavv3XuvryGe0SJsbMiP1DHKutUzF3pTfPwc2m7XGacWM7e73+MT6ZD9l4hiNNDFq2OVl49i3A1cITjp3JXPeTrz2ZlIDGzQQRk7mvqeTqKbH9ew5zouqRV66cXDMkv14vz6PlsEJrcrAUioN2homAoC4yCRtA7tfFe45RGZH9RAhGem65ONWOZeNJBB6YMkiGzypFxSyoJL8He0gwMpyW+6W0WXWFG9k4xWtJy85uQq5Rjth3rKKBKJODW9U08zfsQGRuOTOgZ5zav5dma8A+ghARPObUS2K8CoZdeNvci/Pb/RZvpC+QD1BNAIzXbW3jXAPc0kaErQhaRKEj5LDLsnlo7usw87G1tLdLR0CayJV2YhjEfMDpqgwGm8oWCsNZZIyY8lsKySBdFMWFKTmbg/7x0cijlHyNAEZmgM4xscpOYwAFdT7U=
  template:
    metadata:
      creationTimestamp: null
      name: traefik
      namespace: networking
    type: Opaque
