apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: traefik
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`traefik.internal.mmontes.duckdns.org`)
      services:
        - name: api@internal
          kind: TraefikService
