apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: ceph
spec:
  parentRefs:
    - name: traefik-internal
      namespace: networking
  hostnames:
    - "ceph.mmontes-internal.duckdns.org"
  rules:
    - backendRefs:
        - name: rook-ceph-mgr-dashboard 
          port: 8443
