apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: rook-ceph-cluster
spec:
  releaseName: rook-ceph-cluster
  chart:
    spec:
      chart: rook-ceph-cluster
      sourceRef:
        kind: HelmRepository
        name: rook
      version: "v1.14.9"
  interval: 1h0m0s
  values:
    operatorNamespace: storage
    clusterName: rook-ceph
    toolbox:
      enabled: false
    monitoring:
      enabled: true
      createPrometheusRules: true

    cephClusterSpec:
      cephVersion:
        image: quay.io/ceph/ceph:v18.2.2
      dataDirHostPath: /var/lib/rook
      mon:
        count: 3
        allowMultiplePerNode: false
      mgr:
        count: 2
        allowMultiplePerNode: false
      dashboard:
        enabled: true
      crashCollector:
        disable: false
      logCollector:
        enabled: true
      resources:
        mgr:
          requests:
            cpu: 100m
            memory: 512Mi
          limits:
            memory: 1Gi
        mon:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            memory: 512Mi
        osd:
          requests:
            cpu: 500m
            memory: 2Gi
          limits:
            memory: 2Gi
      storage:
        useAllNodes: false
        useAllDevices: false
        nodes:
          - name: worker2
            devices:
              - name: nvme0n1
          - name: worker3
            devices:
              - name: nvme0n1
          - name: worker4
            devices:
              - name: nvme0n1
      placement:
        all:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
              - matchExpressions:
                - key: node.mmontes.io/type
                  operator: In
                  values:
                  - compute

    cephBlockPools: []

    cephBlockPoolsVolumeSnapshotClass:
      enabled: false

    cephFileSystems: []

    cephFileSystemVolumeSnapshotClass:
      enabled: false

    cephObjectStores: []