---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: alertmanager-telegram
  namespace: monitoring
spec:
  encryptedData:
    token: AgCSzAB90JCofBMlJz4iVJ7T6FhA2us8RgY1p5GlkmAsjmQQ4Hcuf7wFLP2uK4usM6/jpwbrD1OWKkRwfEZd6Mikg9ri+FHVSPECpOGXca+96Fl5Zvi6d5kfogL1HmjHzB4mAWvoKvvE1C280r4iFX2+zDHX7mDnJ76hm+Z97905AavP/onGk9Dav9V8mdcY/v3Sgymo4z9LdlGV86/QGzxLOEbZ2G7EDrxr1iCDg0YYc8L34Z1Na5f/yK6hT9D8KiG9CyYzfa5rvM7Rqbw8UrKjbHOAxV9n5Fs+X0P+31whkjKQaDoZ3o8LqxAajolVS4fkrWg+MDiYiS4d0jliQRst8ADQ190+pfKkw08wrYvho9L7k7uWc0ew4HpT4lJmq/rtTMrH5vq3fEw5RaCdas3IElaOS46nVBb6N1mp+jx8ttXm8LuEYB2ri63SGfaT9BRxScNWkQfwR7gKkLxQyThrQZ6tM6I+YwY4u7Z0DQYMI3FNJdsUFqY4l/As/vNuHjoQ1CJDSqPjX0liQjq+3JuveQ5tbZDnqB1ngpTUWbDYdmUj8CMQlAPo+9hKJezC8wE5W+q8xtyuWophwMF8tpyeCQfJ6oeBWxNp60Y31VHxz8D/73Ft76iGF0ebCtVStXqg3RiZcoit2uzTo8H6W5qPquApqFDvivmRd6MLTxkbh2gQt5kjt973Xc0XmwzEXhsMjyKoOxjVzvfUBugc7yDz2r2Kuef5Fug1IRKBbSTEln9W3uVCooPoHtEKSlTT
  template:
    metadata:
      creationTimestamp: null
      name: alertmanager-telegram
      namespace: monitoring
