apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: alertmanager-multica
spec:
  route:
    groupBy:
      - alertname
      - job
      - namespace
    groupWait: 30s
    groupInterval: 5m
    repeatInterval: 168h # 1 week
    receiver: 'null'
    routes:
      - matchers:
        - name: alertname
          matchType: "=~"
          value: "InfoInhibitor|Watchdog|NodeDiskIOSaturation|HighGpuUsage|InstanceUnreachable"
        receiver: 'null'
      - matchers:
        - name: severity
          matchType: "=~"
          value: "warning|critical"
        receiver: multica
  receivers:
    - name: 'null'
    - name: multica
      webhookConfigs:
        - urlSecret:
            name: alertmanager-multica
            key: url
          sendResolved: false
