apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: alertmanager-telegram
spec:
  route:
    groupBy:
      - alertname
      - job
      - namespace
    groupWait: 30s
    groupInterval: 5m
    repeatInterval: 12h
    receiver: telegram
    routes:
      - matchers:
        - alertname =~ "InfoInhibitor|Watchdog"
        receiver: 'null'
      - match:
        receiver: telegram
        continue: true
  receivers:
    - name: 'null'
    - name: telegram
      telegramConfigs:
        - botToken:
            name: alertmanager-telegram
            key: token
          chatID: 565598
          parseMode: MarkdownV2
          disableNotifications: false
          sendResolved: true
