---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: alertmanager-multica
  namespace: monitoring
spec:
  encryptedData:
    url: AgAjV7m2/K8Oz7q476E4rk4BUpnpOLLjnAv5gxGXPwEdNYjCs29zxe85gm+s2Ab45Yy0N9wK/EP47ErweriYFaJAdb9L9Tx9DoNTTPiZb5FslFKcgRysFwVq7PDMN5fDSyCDjMJO8dIh6eQFB9vKCxuLwn/R6yQhYOZN8xYBalxylx8O0BhJwh2sOAI++9r9nY/Fjznmon7VHrlJeQ4Iw3pmZSlsGyMl/r9pBAGy77nfRd+WCSD4pBK6UwVfjkVp7kT3YDX5tDWeMumrO41uchK2fB/ltVzTXowKGrAgu/7Kc9tazd2y0fOCeQ3wXxqdBA3kJ7RvxFuXmQt2OB8vt5MQ9lwimGvauOYORVBX2axtWDg66qpuo4RpSS8jzyqRIg98jByhtSaDmRbrSkHZfuexXAPpqsIGDN4exL7SDUmU/5W1go1mfGAOcuXwn/vCJxo27BCMHGgOIEnD3zTXd4ltYA1S7hqrhUH1TyBIkeNwWxvZeWlJTmQ6FIPJvfg75Fb1CExfibCp4S0lHlhUR+Fpvcji0w6uRny2NWv7aj24aPUKBYZDNH9Rv2oo8RRWsEvCptu+LDh0uXPwdMlIWgC67jNDFKv8T+8P4nPCYYOZYu4iSNm7cJs32RwGW7OtTGJVQluadIkdm3b5C2YUTHqOAJ8OVEAJgQstF21IJfF057KspVpVN0EQ2cmowhVZbJKE9/0rp52ESE3wBiaLZYNobrx4DJA6aCKZaZ39w0xTcbfHlgLwuSM6EdxUcsNEwjU7fAh0Al5ZoK7FznV2q+nkIMSgR/72cRVXR/Ve0yaMChiTgfSEIZMGpLZYqpnR1szKLPaa9E3jXDFlzzIy9mdkB63zfg==
  template:
    metadata:
      name: alertmanager-multica
      namespace: monitoring
    type: Opaque
