apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: alertmanager-multica
spec:
  route:
    matchers:
      - name: alertname
        matchType: "!=~"
        value: "^(Watchdog|HighGpuUsage|NodeDiskIOSaturation)$"
    receiver: multica
  receivers:
    - name: multica
      webhookConfigs:
        - urlSecret:
            name: alertmanager-multica
            key: url
          sendResolved: false
