apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: alertmanager-multica
spec:
  # See: https://prometheus-operator.dev/docs/api-reference/api/#monitoring.coreos.com/v1alpha1.Route
  route:
    groupBy:
      - alertname
      - job
      - namespace
    groupWait: 1h # require sustained firing before the first issue. This is very expensive, as it requires the whole GPU to load the model.
    groupInterval: 168h # 1 week
    repeatInterval: 730h # 1 month
    receiver: 'null'
    routes:
      - matchers:
        - name: alertname
          matchType: "=~"
          value: "InfoInhibitor|Watchdog|NodeDiskIOSaturation|InstanceUnreachable|HighTemperature|HighGpuUsage|HighGpuTemperature"
        receiver: 'null'
      - matchers:
        - name: severity
          matchType: "=~"
          value: "warning|critical"
        receiver: multica
  receivers:
    - name: 'null'
    - name: multica
      webhookConfigs:
        - urlSecret:
            name: alertmanager-multica
            key: url
          sendResolved: false
