apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: alertmanager
spec:
  # See: https://prometheus-operator.dev/docs/api-reference/api/#monitoring.coreos.com/v1alpha1.Route
  route:
    groupBy:
      - alertname
      - job
      - namespace
    groupWait: 5m
    groupInterval: 15m
    repeatInterval: 24h
    receiver: telegram
    routes:
      - matchers:
        - name: alertname
          matchType: "=~"
          value: "InfoInhibitor|Watchdog"
        receiver: 'null'
      - matchers:
        - name: severity
          matchType: "=~"
          value: "warning|critical"
        receiver: telegram
  receivers:
    - name: 'null'
    - name: telegram
      telegramConfigs:
        - botToken:
            name: alertmanager-telegram
            key: token
          chatID: 565598
          parseMode: HTML
          disableNotifications: false
          sendResolved: true
