apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mariadb-operator
spec:
  dependsOn:
    - name: mariadb-operator-crds
  chart:
    spec:
      chart: mariadb-operator
      sourceRef:
        kind: HelmRepository
        name: mariadb-operator
      version: "0.38.1"
  interval: 1h0m0s
  values:
    logLevel: DEBUG
    extraArgs:
    - --requeue-connection=1h
    - --requeue-sql=10h
    - --requeue-sql-max-offset=1h
    - --requeue-sqljob=30s
    - --requeue-maxscale=1h
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
    pprof:
      enabled: true
    webhook:
      cert:
        certManager:
          enabled: true
          issuerRef:
            kind: ClusterIssuer
            name: homelab
      serviceMonitor:
        enabled: true