apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mariadb-operator
spec:
  chart:
    spec:
      chart: mariadb-operator
      sourceRef:
        kind: HelmRepository
        name: mariadb-operator
      version: "0.29.0"
  interval: 1h0m0s
  values:
    logLevel: DEBUG
    extraEnv:
    - name: MARIADB_ENTRYPOINT_VERSION
      value: "10.11"
    image:
      pullPolicy: Always
      repository: mariadbmmontes/mariadb-operator
      tag: v0.0.30-dev
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
    webhook:
      image:
        pullPolicy: Always
        repository: mariadbmmontes/mariadb-operator
        tag: v0.0.30-dev
      cert:
        certManager:
          enabled: true
          issuerRef:
            kind: ClusterIssuer
            name: homelab
      serviceMonitor:
        enabled: true
  postRenderers:
    - kustomize:
        patches:
          - target:
              kind: ClusterRole 
              name: mariadb-operator   
            patch: |-
              - op: add
                path: /rules/-
                value:
                  apiGroups:
                  - ""
                  resources:
                  - pods/logs
                  verbs:
                  - get
