apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mariadb-operator
spec:
  chart:
    spec:
      chart: mariadb-operator
      sourceRef:
        kind: HelmRepository
        name: mariadb-operator
      version: "0.31.0"
  interval: 1h0m0s
  values:
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
    webhook:
      cert:
        certManager:
          enabled: true
          issuerRef:
            kind: ClusterIssuer
            name: homelab
      serviceMonitor:
        enabled: true
