---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: operator-oauth
  namespace: networking
spec:
  encryptedData:
    client_id: AgARwcxlYP9F6c2n6UIoSFfAusnf7y/Ob24Y6Q1qWQmdnD96xcpSD2WxycVKledFf/JLqAcOk6Ciz5SHbDsBoe8o3BFx0eo2Oxe0UKXUmxdeT0DiuZmzYPkltUgz7rRP5Ux1kqkNMgm87hgCyt6oi0pYavbkeZRoVRM8Qb6v8UDpnDkeMpGOg55/pDmihxut5xIiwJNUKVSDhicicKwrBjfzQLyCvKSrvMOmu8TAcuPLyEXfK2x+FCGhhJsWT/HqDioWH5NQA25wJhFBfxPyalG8oXUNgXgv4mVjjE2yFt6kRYMRD+2PzsQNAFHikF+yCa5ZT/pKuMg1W2pdkT8+6Zuu3wqpt5lYaoLcyBqVbs/z4p3gkuk5HmllEGtOj8oypz4/M8girDGmHouF/6MaBSGn/smCLJt+J2Ypz9PDTVeHls/NE2aUJIN19F9lE+cSX+3xtmSIHM4mCwIAsR5fWlE2KtL0hJnVdOHaMTx0+m+mTf72NbT7wwt6aVQ/xtRoKkbe5ACca5FH3HPVq/PcqyrVzFslw0uG13ayVdro3RL4VXZ1iCzkwThLBQIQTB9iFAvT5TbYfJeHCbuiVin5kD4ucuGnX72CsMls79zWDSOHLYokaSKcv8T6NnYGgq1IY7vgIarCyun6+2Bgz+Le3NiA+iOfkM5GLsyhS5MUz8/RuCNM7Bg7lsbvS1UFWnNydParTtb66vn/w9rqXQYRtV8nBw==
    client_secret: AgAD09DQ0OViUOPgjZ+YdvBtcl0uAjKs8nRkGA76WNdv4yxJ9gx2tprZCOqznzNtu6m92t0CiBKucB4pigZ1Y5tNcDVgf6uISMDeAmGl4rb04xXHCSvwrWtoBW1frrDy45YKIoVv40jpu6xTHXguHinDi5uRaIHtHed7CelKRUvtVDjd6SpTUpHjz5UhjJM8DvRLeCheSFMrIBx3fxg7HY9OXlL9mo2sFf4j7tzRXGyDTYEJarnV0xzgP9IMr+9ViyAZbPag4Xi16nZ9YIRe63zpZ/myxENEx/Dxl21FGP4ha5I6ffO3MY3ItkNQLxwUqUtMZyBrbu23pHgjUjKvzjbvAyqzRDNzWYNS4By4MeR5yIE/8ICRnlkiLYhntGop3771klabnCd29snFP02I4YxN8X0hu3LEpXyWgm3n8TG5ckwvbl/xc63CgTbt5VvnAG++f36ukrVbFz/UuPKkLdaOSuw9zBSM477UxQYhupR9WohOhDZ6QkcvKjKRtorpRzTW1RiwIyz+97V8yiEwnqU3/J7f0Yl1yTu2Nq3jkHXtzqWr5AWkXblOXIovVn7rfy4Q99f4bc6jq4BjACgkx5pHG64zQfAQSsDQR3/fyAsGafGPW30p2XKnzmdmF8ayOB3GGIs/kiJpapEFnDU2gbmIRm4UC2b856kLTVxWfArMLh89eoz0it3PNH3YjNzdR+TsuuXn0m1ccHDFWgFvijHpCtAxFWnAQJNb1UEPDCgnt/kLRtv3qRw4aUcuWVYDW+2rQKZwbwp9Cj/XzYyStlw=
  template:
    metadata:
      creationTimestamp: null
      name: operator-oauth
      namespace: networking
