apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: tailscale-operator
spec:
  chart:
    spec:
      chart: tailscale-operator
      sourceRef:
        kind: HelmRepository
        name: tailscale
      version: "1.66.3"
  interval: 1h0m0s
  values:
    installCRDs: true
    operatorConfig:
      defaultTags:
        - "tag:k8s-operator"
    proxyConfig:
      defaultTags: "tag:k8s"