apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kubelet-csr-approver
spec:
  chart:
    spec:
      chart: kubelet-csr-approver
      sourceRef:
        kind: HelmRepository
        name: kubelet-csr-approver
      version: "0.2.4"
  interval: 1h0m0s
  values:
    providerRegex: ^.*$
