apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: edit-ingressroutes
  labels:
    rbac.authorization.k8s.io/aggregate-to-edit: "true"
rules:
  - apiGroups:
      - traefik.containo.us
    resources:
      - ingressroutes
    verbs:
      - get
      - list
      - create
      - delete
      - patch
      - update
