apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: edit-namespaces
  labels:
    rbac.authorization.k8s.io/aggregate-to-edit: "true"
rules:
  - apiGroups:
      - ""
    resources:
      - namespaces
    verbs:
      - get
      - list
      - update
      - patch
      - create
