apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: view-crds
  labels:
    rbac.authorization.k8s.io/aggregate-to-view: "true"
rules:
  - apiGroups:
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions
    verbs:
      - get
      - list
