apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: minio-operator
spec:
  chart:
    spec:
      chart: operator
      sourceRef:
        kind: HelmRepository
        name: minio-operator
      version: "v7.1.1"
  interval: 1h0m0s
  values:
    operator:
      replicaCount: 1
      env:
        - name: PROMETHEUS_NAMESPACE
          value: "monitoring"
        - name: PROMETHEUS_NAME
          value: "kube-prometheus-stack-prometheus"
      resources:
        requests:
          cpu: 200m
          memory: 120Mi