apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: external-snmp
spec:
  staticConfigs:
    - targets:
        - "10.0.0.50"
  metricsPath: /snmp
  params:
    module:
      - synology
  relabelings:
    - sourceLabels: ["__address__"]
      targetLabel: "__param_target"
    - sourceLabels: ["__param_target"]
      targetLabel: "instance"
    - sourceLabels: ["__param_target"]
      regex: "(.*)"
      replacement: "${1}:9116"
      targetLabel: "__address__"