apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: external-blackbox
spec:
  jobName: blackbox-exporter
  scrapeInterval: 1m
  staticConfigs:
    - targets:
        - "https://google.com"
        - "https://iot.mmontes-internal.duckdns.org"
        - "https://github-explorer.mmontes.duckdns.org"
  metricsPath: /probe
  params:
    module:
      - http
  relabelings:
    - sourceLabels: ["__address__"]
      targetLabel: "__param_target"
    - sourceLabels: ["__param_target"]
      targetLabel: "instance"
    - targetLabel: "__address__"
      replacement: "10.1.0.40:9115"