---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgresql
spec:
  enableSuperuserAccess: true
  superuserSecret:
    name: postgresql-super

  instances: 1

  imageName: ghcr.io/cloudnative-pg/postgresql:18.4

  # ---------------------------------------------------------------------------
  # INIT — uncomment this block only when a init is needed
  # See: https://cloudnative-pg.io/docs/1.30/cloudnative-pg.v1/#bootstrapinitdb
  # ---------------------------------------------------------------------------
  bootstrap:
    initdb:
      database: app
      owner: app
      secret:
        name: postgresql
      walSegmentSize: 16 # 16MB, default

  # ---------------------------------------------------------------------------
  # RECOVERY — uncomment the matching block only when a recovery is needed
  # See: https://cloudnative-pg.io/docs/1.30/cloudnative-pg.v1/#bootstraprecovery
  # ---------------------------------------------------------------------------
  # bootstrap:
  #   recovery:
  #     source: postgresql
  #     database: app
  #     owner: app
  #     secret:
  #       name: postgresql
  #     recoveryTarget:
  #       backupID: 20260829T124511 # From Backup status CR or s3://database/postgresql/base
  #       targetImmediate: true
  # bootstrap:
  #   recovery:
  #     source: postgresql
  #     database: app
  #     owner: app
  #     secret:
  #       name: postgresql
  #     recoveryTarget:
  #       targetTime: "2026-08-29T14:00:00.000Z" # RFC3339 or PostgreSQL timestamp; no timezone = UTC
  # Where backups and WALs are read from.
  externalClusters:
  - name: postgresql
    plugin:
      name: barman-cloud.cloudnative-pg.io
      parameters:
        barmanObjectName: seaweedfs-s3
        serverName: postgresql-1

  # Full physical backups + WAL archiving to the SeaweedFS S3 store via the Barman Cloud CNPG-I plugin
  # Where backups and WALs are written to.
  plugins:
  - name: barman-cloud.cloudnative-pg.io
    isWALArchiver: true
    parameters:
      barmanObjectName: seaweedfs-s3
      serverName: postgresql-2 # Must not match serverName in externalClusters, otherwise restoration will fail.

  storage:
    size: 10Gi
    storageClass: topolvm

  certificates:
    serverCASecret: homelab-bundle
    serverTLSSecret: postgresql-tls
    clientCASecret: homelab-bundle
    replicationTLSSecret: postgresql-client-tls

  monitoring:
    customQueriesConfigMap:
      - key: queries
        name: cnpg-default-monitoring

  postgresql:
    parameters:
      shared_buffers: "256MB"

  resources:
    requests:
      cpu: 500m
      memory: 1Gi
    limits:
      memory: 1Gi

  affinity:
    tolerations:
    - effect: NoSchedule
      key: node.mmontes.io/type
      value: compute-large
    nodeSelector:
      node.mmontes.io/type: compute-large
