apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgresql
spec:
  enableSuperuserAccess: true
  superuserSecret:
    name: postgresql-super

  instances: 1

  imageName: ghcr.io/cloudnative-pg/postgresql:18.4

  bootstrap:
    initdb:
      database: app
      owner: app
      secret:
        name: postgresql

  storage:
    size: 10Gi
    storageClassName: topolvm

  certificates:
    serverTLSSecret: postgresql-tls
    serverCASecret: homelab-bundle
    clientSSLSecret: postgresql-client-tls
    clientCASecret: homelab-bundle

  monitoring:
    customQueriesConfigMap:
      - key: queries
        name: cnpg-default-monitoring

  postgresql:
    parameters:
      shared_buffers: "256MB"

  resources:
    requests:
      cpu: 500m
      memory: 1Gi
    limits:
      memory: 1Gi

  tolerations:
    - effect: NoSchedule
      key: node.mmontes.io/type
      value: compute-large

  nodeSelector:
    node.mmontes.io/type: compute-large
