apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: database
resources:
  - certificate.yaml
  - cluster.yaml
  - multica-sealedsecret.yaml
  - multica.yaml
  - podmonitor.yaml
  - sealedsecret.yaml
