apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: multica
  namespace: database
spec:
  encryptedData:
    password: AgCQyCEln3hQFetAZeWww1HmXFvRHft3H09ylqLFDY+A9v5ZJf6LlZ4KJc8vWGzeS6JXvf354OydLysGwfKkHHrMJB8rgyUQtSuhh11B/eqJuB+XcnC9g5s/DvUA8HexioLxSg/geHLtg92vn/Y2VTem3OJMsQ39Cpo6Cin4wLwi+QsX7Y8mSisDyBBHBHwvK06i4OwXN74FE45A0y0Z5EkT5yDyvcd3PAa6vYnW4oT50QIUcIRZPTpFbu+u4hcDrgMNS5K20KGbGygrcESI/m6OM/fUcLr/5mFQVIJQPPS21DIdwDGfrArreKa18mvqj2ET+dZIlfuiMfoCdYcckRoCvFQB/U0JrACKIqvPcw+BxU4HnbfKeG44O3lOnNlU0nAM/jP7kYKfZdMO3DeLyyj32BUL9lE9WYgYXYTExcYyCMuBwBT5cxN2WSHIKyr7TT00aP6lVzraNepFZFqXGnwYT4ew45vCUt4qr1rXQTOTbXlg6MfbhtrDNBujXmcIjLbEXWth7dx2I0YfGyPCYcm0ERsQKAGWD8PJcjhkGfw7AjWWV+NXVkI4EbVkxXLiRRNbE78UHI5fqk3ECBg5h90Z6AMBVMIFQBFX8SB6EBWbgJ4Ey/S9g/Rob81TBNsdQV7U/1lPwm6bdzNkuwcJYgeqlq8NnR4GbmlpF9W+IXkCZLGjPrJdyCFv4HpK8Es5eFWn6CN7rNhHdSEG
    username: AgAwthWuwzPMNYTasIfGgt4antDYxaegnp2wDCQoLDsw6LvDf+Jvma6adSwn4TSeSaGIYZJbhQegm2dKZmV8M9unlQdytB1i74BJMAfIRaM4Hk44V3cGL0yvICbTc3XVMxtOACy0wlbOsySEEwEcyI4d3bBIDR5dnDRhgnVDaKUi7Qd1I4ynt1RXBPaRBMdYOB/6lxbkeKalIvUb18YVoYhs0a4/XedRxjnnXAHiDkjoCSdG89jg+JvTCL7O/tJGI2bVv664XSq/q8bDCwPWmlu85cj7g9sWBt2qW2xNtD9eGioj0MiAf4UBYqhudvsQXEq+qsI/4e8IFFUsppFSW5F3W6lldYYAZ9DkhYzdRpkqfZWX1SgT4yK1C+TCev/X1id/vrCT/tip9wVEyMSrBeJckPNYoteVMtn8A4GB4qrOL0OBYGdpDRCQFj22zsjsEJ0D6HLRn3W/FfEIvevmIOWwJdZt43VLohR2ZA+cHniLSXYUmuVcoD1ckEOT6mb2+omucX3mXZDgOAfI+CCSpJevICUlztYnACWMo1F+t3no+4DCd051rBmODdTuUNuTXnHqFgcmko76gqcdDzMl09d9i6so9p00CoeqpmQF6ip6Zg6LZSYtr1EJ60R7HzS2RvzlgEJ5EdgvrWNWPqZEOujINjdDZ01RT5AYoxqBrWDPxKB2dwu/BlfKWE5Zi9wz1ZkGbZux4pq
  template:
    metadata:
      labels:
        cnpg.io/reload: "true"
      name: multica
      namespace: database
    type: kubernetes.io/basic-auth
