---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: multica
  namespace: database
spec:
  encryptedData:
    password: AgBGqjBhPp3b/gr5AwX3eiW+BgUffSPoVVeaHlp21t5proZ5v24eO/MI7sJINO1wu8qUhvyz6wZQ1eaZhdBbkpxgtY/0+xebFL71RA7U15zKWCnBe05STXzm8ZSU7ck9XXfNadcde12baH1dm/IjY/kHR5XMLpjr3IwC+v/wmEkDs3Mke+QLkfaizqEPdHnL5UH5mFFv24agEOZUxl9j8e5pw55SjGQ0rKeSQ2k6MwfC8xpHHVZE3tV1bOjazr2hjud3iY4q02Po+OpTByIjW8xyPEOFgZZrNHhxAq6KxQf79jlsSTs9z8M4F9N/Imbku6PadBf36sOz/eb+JhMR1VeoQI/1Mjsifvmkgf9lEDvhGIl6A42xqIZUt7FpPsMB2QbBHU7A2d3ys/ovZlvb8EaSWUSbylJYMyzWi+r0nT1IHAMJ2R5H4zqvTS130RSdSss2iNOhMGCxTO8T2ceSAtVkzJGVSLKVWMoJNjK+EzDrBXtCG5G7q6amnkh+dDLpEnPDcFS0vyqZFSDpoGJMyfyz+qYEZ0iunze0xUKJ5KE7s1FZvJKEZp4HzFeIIMRAcZK1KPebtesNp2oxe8kl/h97qbSX238cMjHOXDBxfcx6Hps2IjRpe/3+3ruhk1ZAAXfcJQLDRISq2eo712h3AJ+S3xleOdU24kFIH5haDNRIdAhNxzd0xe1BlDpG0ZazXCIFC35wHplmLOb2
    username: AgAdLd2d0S9z8L57J4ywrSiH6UpCvtU5vDs4pYZAP5/nwoDT1Q3gdyDzX2697CbY4Ugrxe6ha0Nauq7VwFY1skL6KtmBzgw9y+mQ0cj1cL6LZKCVRo2ho/GyqvTVsO/UsO43t554DtHnHgYezdBZeubxG5j9dBObh6QtG45M+2bhD8Nq9kj9rnwxMHpao/t/CJoAg6IsUoCwJie0j3+1c4L71bScKVHkf/cSr/AFFfKGVIEO9xRX8NqmeS8kDyb+czVJ/qSnhq1LUkS7p8+hcdYX92UWafDLb/XYsDXPZuA1cYFRbIhqb8qv60vgUteGs7RKRmeWdj6pl7iu1pP3uYXrm1ebfhu6G4CTeoHDKtrwyuARwdF1O8xE6vtbeipHydabsQ445+qbkJwj6yYhaiJhqUl3sNGMlGgAjxr6aUK/e3Sx5yamy5lEsLthwVpgbR6dW4Hw53Ba1XJORg1JMb1AvmbI1PWKX80upfmRazX9VtAkEaaeAVT4B5y6I9yHt8W+HmtA9gM8vcHbXyBhA0ktr8oE0GLt9yW/xpvVssK2VNZ3zqUQX397tRHNa28KGEx6/tIhqSDaVgwg8twjVbDogv4B9iricNB06RMwwfKO1dXpS+cDTzCarLv+wCIBU2F1rTEtmOd02eRtorsFtDISrB/kEdc1jwAcqHoidqgWXz3tzDkCb+aH6d7SEUwjkVnC4pHs0PMO
  template:
    metadata:
      labels:
        cnpg.io/reload: "true"
      name: multica
      namespace: database
    type: kubernetes.io/basic-auth
