apiVersion: postgresql.cnpg.io/v1
kind: DatabaseRole
metadata:
  name: multica
spec:
  name: multica
  cluster:
    name: postgresql
  login: true
  superuser: false
  createdb: false
  connectionLimit: -1
  passwordSecret:
    name: multica
  databaseRoleReclaimPolicy: retain
---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: multica
spec:
  name: multica
  owner: multica
  cluster:
    name: postgresql
  extensions:
    - name: vector
  databaseReclaimPolicy: retain