---
# S3 credentials for CNPG barman-cloud backups (same SeaweedFS S3 endpoint
# as the rest of the infra). Keys: AWS_ACCESS_KEY_ID / AWS_SECRET_ACCESS_KEY.
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgresql-s3
  namespace: database
spec:
  encryptedData:
    AWS_ACCESS_KEY_ID: AgCeuoERG/CvdxXtrG4gCugIQroYOlfe4oVm0zsSzjddriJLlo77sL0Pv/hBfxAKBsbmNGKGM6L0+kvfTqlrgdzd7Ez1OiHeU7xBdJtfNha394aL09PepbEIm9NeDdZvvOTspCEJ0jILABaXgPbbI/bkw0aB+qE+CjwnKsNE4lOJ4LmZFyRbv80MCZ7IkQ1rQ6c2MOpfNb8kwSD8+gPnZiwjyFOMlSf2rC8IJh0pBOyiq264exmr0EKPJiA2VV0nseHCKhzofTuaV9coeFTPoIs21gC4smmldVDT/kXrhXaOonNIdfu/geFSDOGhEQtKneLCb9Brhc0UOKdjktx+WWiaeyPmoNt6Ko+7on2P4FfzjaapPBQiR9PTfDNUW5NDj5PoUpZSeea1N/jfnyqvjIfuxnzz0dcC7S8XAK/18ijdXj+/u4CBI7I7b9bS4ZtzJdKZolp07ahSpAjbBP2UsSbzuD0FS4mQ8Gn8oJFAl2IYutEJxo08ELaUZrUVqeTwl3OLw+g8lvIcFoaNKZ5q3OFyf0wPrWMKoIDc9hKlPouwlAcyo0HpMg06eTHCzV+R2iq6WPWQmeo/3bt9k9xA5kUGEfuOebfFnr8tDkwqUJTCXX+9AZJpgcJZe3es0el3WV+sjWyri85omkMlXEJZVT+z2cCXmZJebhE6Bi60oPhVHEC7b1bRq7os134C0cqq04jvBQ==
    AWS_SECRET_ACCESS_KEY: AgCeAYrQy2FhAhRrn/5nkezvkjRV4KzpYi7fZ7Fax6DOz/DHejeREYUnySeJ511/AoD+EU9vcWCT0bmhNhcMWKvr1aGseeMT1cNgqVnj4edlPyu9yKTOXJhqB/Is+lwexTGv3M3VFXVXP3wOgD7EgUC5SBABA1uBri3qlAcS5/UI4CpFlOGLYj59YzcpkYp/AgNCrUPFuNLZxDEfwnEhxCh+dmsXUimS0ygrODNw+3pIJcttNt4olwazbTcd5bu+1p0nBraMFLxugH5ivFEIPVLfDHLgBaO4E3fusJ6HXbNRIfLyEVYHUpbnNEhacWn5h9CO+3D4GEXDuQOAH7PRvfpEO+Fy/D3/Hw0YAtzYhpzI2NjWWvm8+dc7gycwI19IHRH3/cyTWCVUZQSPTVZp9zH8jMIlgTGDLDv7y57IRXWzFG2bE69/T/YT6fEg9KHlbb7J5NW4XcYkE2A4lSJT2OuUAx5BUAGNz2+e6mXALnGjbT9iuSVEia19GyWHppgqZXu86excT7qsJIXAJ14TlzzmIzFCuyolnEuIpF+95xmTHqEijS7upjmG3/phvf5MFbR2c6wjzb3XMLF6kmkUnXZeAEyUEAIvtHekByFeUVP9GeUsH6/RnkJTVMO/HXh+ru5JVEudgB9s74J0iM/QqwOl6PTwxN3P2X58CrhsX6PEROVBR/3485eiGUKFD5ytjhT7lITRuZpTKxUHG/72+Vvk6w==
  template:
    metadata:
      name: postgresql-s3
      namespace: database
    type: Opaque
