---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgresql
  namespace: database
spec:
  encryptedData:
    password: AgB6jwTCSYRDlg+5KgD8CfVdUWfcyrhWF83PoEBS3EBykALH5oMFoMgQt/LX9S+xaVoqmte8agl0qjyOF+vjjBw07GVvPVKIfVBSTsklZ7hO8/cfUNeCfzprpJ+8uF5UN8gt1dlWSibMACOi/twHSFYAfokAFwX52ZuD4AQiC/WRIrBt2fKRDrUksHzozXtdMaAaH6+4hDw+q2atIY4gAAhco7wBZk5EXiOCNKwuAHXfEf4HqCUBdBNWgQRJDgMQ3YyetSqqcBhbLlUqpn5IkU4uUzTYtlNyXxONJS0lPQgFjBFcFGq8fsNjD4Q/oX1XEyyMGZG9wRz3gmd517a4LiEJRvXjf1hvsv6NjpHmSbFNAtLkOY2PAnepwvkLgb1klBX1nkgiGw6YXRngXA7F1r5OQlYte7vDrLbs/iYkvSLxeeSqePtnSZz3WWak7iw6HFNB384eti1NryGf+nP1ijS7eV3xh7JeGO7mjiK0qtfY6h86dQ+M4x+qKBG/YDygtyT/5aYZf9c0Y0IB4t66ytk6HFncXiu/OCI+QC3400r2iF22Zcv7QAphQd2uuJ8D6jIJ5mjhj4APNg6sR/MkkE49iHQi+BmBS6zef8Bptf768nWD0wyAdDqzvPkOb3Yq6jIoXXk7iHA1b3OdOIGNg++eYo0x7xbPzry1b8geMZb2AK3tJmBncpOXfcdmm64I1SCkJMcYcHTY9I0iFU6T
    username: AgA/G1rnSTizJtZ3qDLEfpxVe0O+7Kb/5KvEZxT5eYhi28PAXoQWEzLh/TNmsdUPgwx81WpEo8caHAMWMqQftwxCVSIzWZVolLXYhUEJPIHddoE77hL/i92ZkkefiHJkSz8x8ZR/LzwGrOBC5L1WHmw/d4F2ZFLcfl2DOZZ5TZWaGZ0UphEL6VTlnoXOBQi99Tl7zu+wMp7Tyd+MwEJ3S8YeU7wfcJnQ/KGnMukd+e6CkjhR6f2Cprrd8fleL8iAsCrdwjN0US6XTufAXgD1EeoqQwrL1EnFVgo1jjhoJv4N1I6Mo8ofz3TjIrjmj90+5pB2M5xsINj2Z5OYMohccOpWOtrnkC2FRnw9avWxTP5LUb0zAvyxNs4ZJ8UQZu/MfWMchP9YyEFwEZ/v1WxlTKZY+m6b3SuGSB4jLoHyd/fd43Cayl15GUJw6CLoMz4rkd3mJQx24sbvlO/ZdkPyUWa4P6m06JDZWhpg6xw9oVU61te3mViTT8ZC0GNc53xFBFzTdQDTST5exhIF7yr9rZBTJKxbp/G4ThGvSzHHSbs9rJzL1MDSHkfzpBRp4xl9DTuMk5FPtGNMVnFoOaDIWYHaoeT39E+qW/c5Le14kyjMBjrk6JsbBF2KrOu1osD2BLoYErQdYJ7W4JPdWKowgpsph9A3yXKHzWDZZxNOe9OfnExx3P4DPO2gNxLeQDjJpVcTPt4=
  template:
    metadata:
      name: postgresql
      namespace: database
    type: Opaque
