apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgresql
  namespace: database
spec:
  encryptedData:
    multica-password: AgCcZ0IB+cg4ngp8n4YlGGoXhbgMuo25S097O212R1kcHvWebk7+cmURAha6/Qq9c1ZX4hgTHdiPAES6hlcnrAfbJnKUFpa3TwedXgY0BaLyy11M4w3ocCaf5bIjA9IVjMV1Em+RB6zwQWC2BDtwizeoVBUxI6fd18kVCQstkKl5UVnBhpkYjnLnONCa3zKJZB4n0bS2Rn4LLO8h7beW9scJ9Y+nS0Bu5JA0DRhkWQhpyak6NXWk9b1ZCBkhyuJUeRPN9jBza28a38Rw7zmytPyoJrFOD8Folzv64Hu4c4I7Oid7TyV39Iw7tMvttCqsJYQffQ9H47rx1rleJiy0CE80v7eqKEu5+OCFgvDRiOm3XmMbHuT4+ZgabIlodjf2LQP8T5BLWLkG2hK0FIctz3XwSp3FQxDax38AXgAqsicmrUe2Y2y5dfRFJX89kWuBpsHZrtC5Mqi5XKxglXw3eUXQxqwwgHGNLdWCvvSPsMguNgjUBdI6SAdz+OLm2RfzBMR1TRyTP62SwUdZK51aWXnthn4o/18AfLJbbFaE69JUu2QRMSUEYNASZHceY2VxvUADhZB+OdYlMXB7f6CPUaJuCtuB85ALmQwWQowkPTI4bFQ1TOkQyW4i3Iz+pmXJ8gfeD/ecH9xAWjxHp6ef/Uv30hstfQ3NOxodsL6uWeHo3A9vMP0ygWX+vY7GyKW5COX75JamaMs1Swc2
  template:
    metadata:
      name: postgresql
      namespace: database
