---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgresql-super
  namespace: database
spec:
  encryptedData:
    password: AgCfpoLqmUPCXgCgFgn8SmdnW+HHjt5kMquli9+a1v03uUgW2ik+X2rOF1YOEUA01bZiBgBtp/cL6ZQoxvIDYLA49L5MStnRBjN2c6N4v9+E9GdkO+3o1txNDupFE+GXqKt9rf5Q5LokghZfCaXKnD+xhOfsaG1Zl+x/NO1iMJtpz80DuQb0pnvV0FGBbT2g96dP2ydRsccj4GnraSPr6HeE+adz5SmdL2XJUYo25DcMzSG1gmjmyAEDJiFhppc9oRf41tEnnVe8WEBewqNW/+yxTR9B5+Ri7F3eGkz7LZphm/KvYBDnSJQkaxEiqxFaHXL1LiInW2WPQPIymh0f3UOYOLX7mmEhuDng+TRGme0bP2dEbyQBenCTX0AwWR00m35fe8QSJnm4qimn0wQ2kh/p+DK1Bc2NnIcvdcqtx2qwUpWvU0PnNDYWiMifFeIspuNnKRzs/f5UPsYsCzeSlABk+4MKv5L4dh6EQy8KxPLYfJpcAHeRR33YPBjXTOItOc6KqYlq2SGG3PWhC0x3Q7LEGYH73Jhsl+ILlQnMgmf2mXfaM1ygohXNfbpWxIltPzl6je7/h0ZyGsmS3NUv+/p9jA4xSEQqo1Qnl+SOlIsHonZOq2W5Z4EzM27PZTuR7vC8Zz8ZCZXPz+BMlCOYT1TRf9h4Zetg4iCps1j+RPSb1fBVtW5LSpxcS3RucIHk5KhwyCO2aT7ChJWvaa5E
    username: AgBVorKu2UYGvMUMdKvHW8nLtAswaBytpzq2NyuhbUwV0BMolSj0k3pz+nHpX/4FukrFRhiI7ZfDzkFdJkPprYZkkm7gmAreWm8LGqdHP/PSMqLcrx/a69PRE+Pd/xYd1L0yFGGKy6vF7atFipl3QobtwCNZbiQ1bccZH1bq2jE4nQS/2F1Ld3KTipReKv1HlM+Kr95zHyZn3reS9z7RUhQv18q6ew49Odq5ewjhxGrEr5n7zK6Cd3CIRKCfjEoJee/rhsiVrPciVxWFk8fXuDqsX2KWWVb40tFK7gJe1vfWG9DpjNF4Bf+5cda/5HcWVDeDSniUg6bWmu+UdbA2R18i9T6AzAiaTgfgFvyxlnVZG5rQLuROVk9jNp9h1dTCdypN0eCpy546J9IegDdzypuSfV2a/pRalp67BkcBWhJHo38w9NSUk2yggKn1INLU306UnV8i8KLG8u+veBCfBeu2At/46vZGNnX5f17miwWxaMNT6vFxnlMTeaCWtLUvvYqW8Q0LMHhZogHmAy7vEtyswQy3bRm4sFt2kdKvdVOWhHVXjcnS8DfBATP8Wddl2rC0MNqAZPcs32PWHdlc/yYZBngnFwnSUANteAV+VQ2v10gxc6+cDoF6wSdXzS78kDRWPIlfdSHKZGdatgD9YKsHjcNm4iTlXqvq3zkIOB693KffLuEqsF3hkFfWZrnHfyWByQZhlaNq+A==
  template:
    metadata:
      name: postgresql-super
      namespace: database
    type: Opaque
