apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "chartmuseum-init.fullname" . }}
spec:
  {{ toYaml .Values.jobSpec | nindent 2 }}
  template:
    spec:
      containers:
        - name: init-charts
          {{ with .Values.image }}
          image: "{{ .repository }}:{{ .tag | default $.Chart.AppVersion }}"
          imagePullPolicy: {{ .pullPolicy }}
          {{ end }}
          command: ["/bin/sh", "-c"]
          {{ with .Values.chartsRepository }}
          args:
            - git clone {{ .url }} -b {{ .branch }};
              cd {{ .path }};
              {{ .command }};
          {{ end }}
          env:
            - name: HELM_REPO_USERNAME
              valueFrom:
                secretKeyRef:
                  {{ toYaml .Values.usernameSecretKeyRef | nindent 18 }}
            - name: HELM_REPO_PASSWORD
              valueFrom:
                secretKeyRef:
                  {{ toYaml .Values.passwordSecretKeyRef | nindent 18 }}
            - name: HELM_REPO_URL
              value: "{{ .Values.chartmuseumUrl }}"
          {{ with .Values.resources }}
          resources:
            {{ toYaml . | nindent 12 }}
          {{ end}}
      {{ with .Values.nodeSelector }}
      nodeSelector:
        {{ toYaml . | nindent 8 }}
      {{ end }}
      restartPolicy: Never
      automountServiceAccountToken: false
