apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "chartmuseum-init.fullname" . }}
spec:
  {{ toYaml .Values.jobSpec | nindent 2 }}
  template:
    spec:
      # initContainers:
      #   - name: wait-for-chartmuseum
      #     {{ with .Values.initContainerImage }}
      #     image: "{{ .repository }}:{{ .tag | default $.Chart.AppVersion }}"
      #     imagePullPolicy: {{ .pullPolicy }}
      #     {{ end }}
      #     command: ["/bin/sh", "-c"]
      #     args:
      #       - while [ $(curl -sw '%{http_code}' "{{ .Values.chartmuseumUrl }}" -o /dev/null) -ne 200 ]; do
      #         sleep 10;
      #         done
      containers:
        - name: init-charts
          {{ with .Values.image }}
          image: "{{ .repository }}:{{ .tag | default $.Chart.AppVersion }}"
          imagePullPolicy: {{ .pullPolicy }}
          {{ end }}
          command: ["/bin/sh", "-c"]
          {{ with .Values.chartsRepository }}
          args:
            - git clone {{ .url }} -b {{ .branch }};
              cd {{ .path }};
              {{ .command }};
          {{ end }}
          env:
            - name: HELM_REPO_USERNAME
              valueFrom:
                secretKeyRef:
                  {{ toYaml .Values.usernameSecretKeyRef | nindent 18 }}
            - name: HELM_REPO_PASSWORD
              valueFrom:
                secretKeyRef:
                  {{ toYaml .Values.passwordSecretKeyRef | nindent 18 }}
            - name: HELM_REPO_URL
              value: "{{ .Values.chartmuseumUrl }}"
      restartPolicy: Never
      automountServiceAccountToken: false
