apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: traefik-internal
  annotations:
    kubernetes.io/ingress.class: traefik-internal
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`traefik.mmontes-internal.duckdns.org`)
      services:
        - name: api@internal
          kind: TraefikService
