apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: traefik-external-basicauth
  namespace: networking
spec:
  encryptedData:
    users: AgCjGG5Z7opQMCTebfD+wB5gdrJd6by+dK0zIJBDZbxX49waucPEvgS6Wb3Mqy1XEkqVC44/REZ8OowPBWe8sEDp26/0TMacMLWFdwiYcVjXBwzmHqRvhRYY9wL2+btpOVT+7tNJnusPxImmQP+vUdsuGs8SbNRc8v1HJXfP6HUZ8dZ76MUKZPeN/BiT6BT1xmgichQArBHvAFd3aHx96jOWRr8xvhkECpRffHDKeEOUClDaQXFNLkawHyZjnDcegARac5KhcOhxVgrJO6umPT1B528KgS6gdTLpnOy1Sa8xWuPycRmTTE9HpemDscV/dvTmM0AvD6XVZsRNa6kGIW87foCo1xoXzgYHGl3wtAHJ4/XJrLNhZrh/2dPp2RYGmkyhZ156CvVaSZyudAqy5zz0nNtEQ2zSvaa/WixMmklHK1/S1+P60o1eMR9cUaDr0jw6uYX8MmKLBT8OGUxECjNPKzBx+pPq43gWqlrS/mpQ/FluB5GXXxuA8g/wJjkO7Uv04Yj7Zomfv7WbyQ2VquRLzLSjH5GZ95rsLd0mtLrRPRuSyQdoZ8CrvBGqjTEk4xQ3FBpLCTGzqFoAuPd46ytF8GqgmCbSKuDDI0ONTUpEnhIW41AdBmdL+UpcDLf7RDlAtDnCddSSBQFg147UjGCDWGjmkLuovliBwWrHLlKWc/5a10ZqvehBvACLqsjwdWCNNhKsM5XIZ6XJC/qReMp4pLz3dyiqLZcd60RbDHUZVd1n7vCMa93OItEufBU=
  template:
    metadata:
      creationTimestamp: null
      name: traefik-external-basicauth
      namespace: networking
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: traefik-external-basicauth
spec:
  basicAuth:
    secret: traefik-external-basicauth
    removeHeader: true
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: traefik-external
  annotations:
    kubernetes.io/ingress.class: traefik-external
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`traefik.mmontes.duckdns.org`)
      middlewares:
        - name: traefik-external-basicauth
      services:
        - name: api@internal
          kind: TraefikService
