apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: blackbox-exporter
spec:
  chart:
    spec:
      chart: blackbox-exporter
      sourceRef:
        kind: HelmRepository
        name: prometheus
      version: "9.3.0"
  interval: 1h0m0s
  values:
    config:
      modules:
        icmp:
          prober: icmp
          timeout: 5s
          icmp:
            preferred_ip_protocol: ip4
            ip_protocol_fallback: false