apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: grafana
spec:
  parentRefs:
    - name: traefik-internal
      namespace: networking
  hostnames:
    - "grafana.internal.mmontes.duckdns.org"
  rules:
    - backendRefs:
        - name: kube-prometheus-stack-grafana
          port: 80
