apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
spec:
  chart:
    spec:
      chart: kube-prometheus-stack
      sourceRef:
        kind: HelmRepository
        name: prometheus
      version: "55.5.0"
  interval: 1h0m0s
  values:
    prometheus:
      prometheusSpec:
        serviceMonitorSelectorNilUsesHelmValues: false
        externalUrl: https://prometheus.internal.mmontes.duckdns.org
        retention: 7d
        storageSpec:
          volumeClaimTemplate:
            spec:
              storageClassName: local-path
              accessModes: ["ReadWriteOnce"]
              resources:
                requests:
                  storage: 20Gi

    alertmanager:
      alertmanagerSpec:
        useExistingSecret: true
        configSecret: alertmanager
        externalUrl: https://alertmanager.internal.mmontes.duckdns.org
        retention: 120h
        storage:
          volumeClaimTemplate:
            spec:
              storageClassName: local-path
              accessModes: ["ReadWriteOnce"]
              resources:
                requests:
                  storage: 5Gi

    grafana:
      admin:
        existingSecret: "grafana"
        userKey: user
        passwordKey: password
      plugins:
        - grafana-piechart-panel
      dashboardProviders:
        dashboardproviders.yaml:
          apiVersion: 1
          providers:
            - name: "default"
              orgId: 1
              folder: ""
              type: file
              disableDeletion: false
              editable: true
              options:
                path: /var/lib/grafana/dashboards/default
      dashboards:
        default:
          node-exporter:
            gnetId: 11074
            revision: 9
            datasource: Prometheus
          node-exporter-full:
            gnetId: 1860
            revision: 29
            datasource: Prometheus
          traefik:
            gnetId: 11462
            revision: 1
            datasource: Prometheus
          go-processes:
            gnetId: 6671
            revision: 2
            datasource: Prometheus
          go-metrics:
            gnetId: 10826
            revision: 1
            datasource: Prometheus
          pihole:
            gnetId: 10176
            revision: 2
            datasource: Prometheus
          flux-cluster:
            gnetId: 16202
            revision: 1
            datasource: Prometheus
          flux-control-plane:
            gnetId: 16203
            revision: 1
            datasource: Prometheus
          cilium-agent:
            gnetId: 15513
            revision: 1
            datasource: Prometheus
          cilium-operator:
            gnetId: 15514
            revision: 1
            datasource: Prometheus
          hubble:
            gnetId: 15515
            revision: 1
            datasource: Prometheus
          cert-manager:
            gnetId: 11001
            revision: 1
            datasource: Prometheus
          metallb:
            gnetId: 14127
            revision: 1
            datasource: Prometheus
          mysql-overview:
            gnetId: 7362
            revision: 5
            datasource: Prometheus
          mysql-replication:
            gnetId: 7371
            revision: 1
            datasource: Prometheus
          mariadb-galera:
            gnetId: 13106
            revision: 3
            datasource: Prometheus
          mysql-quickstart:
            gnetId: 14057
            revision: 1
            datasource: Prometheus

