apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
spec:
  chart:
    spec:
      chart: kube-prometheus-stack
      sourceRef:
        kind: HelmRepository
        name: prometheus
      version: "33.2.0"
  interval: 1h0m0s
  valuesFrom:
    - kind: ConfigMap
      name: kube-prometheus-stack-config
