apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
  - alertmanager-httproute.yaml
  - alertmanager-sealedsecret.yaml
  - blackbox-exporter_helmrelease.yaml
  - grafana-httproute.yaml
  - grafana-sealedsecret.yaml
  - helmrepository.yaml
  - kube-prometheus-stack_helmrelease.yaml
  - prometheus-httproute.yaml
