apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - sealedsecret.yaml
  - helmrepository.yaml
  - helmrelease.yaml
configMapGenerator:
  - name: kube-prometheus-stack-config
    files:
      - values.yaml=values.yaml
configurations:
  - kustomizeconfig.yaml
