apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana
  namespace: monitoring
spec:
  encryptedData:
    password: AgBCAR8XBJqCnSzyEjrTZVSl45/2H7vcTrEUXh1y3QAzhV9LQM7aeVndpPrSRvqXe24npxY2s02E4y7az23uturUen4fqH0sTXdfEZmpNCm8r8bI+D1h4ao3RxE88580pePwePEomB47reEiwIEPYOwNE7Th+6sAuZWj3OTPUIrtvMGcLO33F8LAIKoUCglt/wPsO6lSDOKhHUHkE9k3MewIKnqrMw/GecKbjmUSw7DTOmC64vuuejdPEm0bQqGym0ol7QrK1TcTCEjNYNN9YWDaRgSVoBBhlob6VOLolXSs7TZ4VSjaErDdb3IiTxsAh4ShDxpjJeiTC9CcQQeb/weWtPtT0qcC8WNWsSR6PjywYi8zfEe+Xpf0RXWW9j7kukv6J0YkcfBl/TysK6EjltyEFYyUGi3QFrQfgOwUL8fIo9VtDxHfSNJ/DWKLMHBwcTl4jGWuuRwnWjD+4jNFVYe4UA8pN6VTb2DFo6h2bivSSOzPfWjsTyu6mxUY0ghNuAY+Vpmfpmi+pyWnVQqCFMyeZeTqcia63QIqQi+J0Rc9ywnjphn/mSpao9b0Twjp9T89g1S5mYpvT+aNvAfNP26zO/s89iJu4kUkW1yXfqAKF8zJVUG4I6WzZ6LhS04BBmP7LopH3+cTR8PbUw5OTepWwHvzvRFaQJueIbHPlSv0nRNaY6vvvmLHqEAoFyYjTRGqhTlvHKOP6DQZko7TomX0bRBIsQ==
    user: AgCKu3MNcLsNcuJnaUabEOExmBdMZCZGVkZeWYS+1qhpkchosNkObW1j1K5PDfGxXibRkpxEjK9TlplwfFUdc1lF396MOokGnBWuhASudVJxJlQCLahWXouCLUeop2cqy2MNA+5bdPc3vaSHBg/qA8WWyFYwHTPHpyauIo3cpq14LnxqjQviuO9Zr8skc/Pu2lG1g1TXfJi+kYNiOHyr/0VXiWsDPHN2mr1K2BMojsG7DnD9TEz+l8K+N3hlL/OIFXSlN1q9Rz4je3xaUdnYfdBA85C/zZnbLqLmN9ZiIIPdABtPXipzgG4JWmhwOCLmjqltbws7iyCJ63ZpyuV/3iEGJK6BO2y6jdm4Y29pxwWxBQdcvpDA8S4Prv5XnRGeqYVNZDDaUx7+xXSXKBg5HVb6sr/hAMFHtiaNevVRgzPQZh3bXiOGJ8EFAtlrnIy6Yj3Raje1s+VbKrpX5hGlq0EZ8TjuwTZR8KrNV5G8RDo/uC84E7qs4oCtPWfP2RdHyGRjiJR7SVpNE+JCy6653+qskPHHeEafzkBaE60dCYfyXBDm4peNJDPB0IwOWFNDY0ZQJCe8LAvF98h5zfEdcQ2J3qM/3g1HjSkzImaZxIVlvGSv6qoG1NCn3oDpBoTvFJMpMOJqdDW53XkJxynq5qJ+qQ6TSeHiREKp40GPSYiYf4mUfnCY/xdDmgnKUZh04f+lhaPnWA==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: grafana
      namespace: monitoring
