apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana
  namespace: monitoring
spec:
  encryptedData:
    password: AgBJpgC1JMQIiIgKnq/6FQnswXyYvPeYl+FnMu9QfZSUbs22woWzVovzaQ7SLhEbsIkTMlSUFPolW2+W5/oQSKUfRGY7a2XH7Ta3l7/XcgmKMdcUzE7Guz9y8d672zSzz+hgjvqb3FZYnPtnOQxL1epz7eLCf14sAPFmO6zRlAVZlt1r0c9f5aftgORQyLPfthmazl8KvhtKI/sIBRJM/KrOKFJEANq0RlNAa4fK6jCdug649WrmH1nv+s31iz6nIaAOw/3m5JRg2GiKDIg736f1N8qiRnCV30rOqMkrMLdTMWKeg+B7EWCe0DefjVH8ORat8v35Vup1aQ3xo+qUicfEcq2di3Tq25craJ4hXsCf1Y3DaNnuG4z2W1e07Ye3hy2rLZ7Taf1ETWP/6LFEYHhh16dSqv9w0Gsali80ZutGJkMqHUbC6w7kbd623DgKUTcOIlpztTpk98ou1TF3mfWbcVryEMcocu2dqY9IiFm4bT45RlbVR8Xwa3trlBL718lxeWmxqISWErRYHEsTrtmRbA21Br2mS4v/HRF3GvdS2xJhtC0ECqYsDPCBZXU4ZTf8s2hbu5q6xMKVaHdht2rDEviQQriM0QeEeRpbxs7zOYPvEdqS4QZ/T5Ue+U6imBjqgCLe4gFUl4iTPrV/3uTKMBH/slYSgiMhUBEkwAcHyjCe4ICfQi9ZI30CqClZeWzORfog6ccKmyI4i4IhbUU3g4uHxw==
    user: AgBBygDHhobLdRq2642gbV6PSJd9bKpxXG1shaFmb3JNLsrJkLzL9M8xOmJMcCHJb5sfLtamprWvtFWgjrvdbs9uLFkiBCsCSt8ZAy9446yKUlCvTJyamexipp9K8fMT022vyIZtODpntAepNqobFObiVokQAiAcg+ptDiKA+teJ5ZhGJ+hgkXGrkZl77bKqNGSoISjbe7Rr2Ib4wLH6PypglBH7xFnM5y5ajSG89oKPTU/2OEo8yVXMLVO9/Oqpk8ciwb1eHzSSCxckvD33HQioaVdBY9LeR/BM/2ckKIewKA6GpHlhxMGHcgN32bQbfDNbcEx9nlh7d0ILP+0Pt1Ook2DkNKZ+oMjMZ+c94JVcpGagoyW3wZNBGl5KnK1ARq4xxHpuRdqnPsX7UdGrJeBIXNqoHYSn4t5s694HSxWMoGm33r08XvmxYUOAevLmqUnmLoyOAz7KVRZhbASkC/mp1MZg41mbFLUIpIxVYiqo41mhwjZu8FhaDoFkXiWRDAkjgwXeKQpzETYqtktZZWBQfkKqd3KdCR7UgEPfUaXaa4wGdj8TrVjj/CmO69cGkF/pl3UuesdKax0RHC0dRVvOltZeW4tWfZHVYVIJDP1rpYNwqU1RDb+bWhzerU2eesWxWlfDLMtAGCU0D8HfcrsLBse/LSU/mXw3M2c9vllKYZE/66zt/Sog+aOsNJqk+8PYkgr/zg==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: grafana
      namespace: monitoring

