apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana
  namespace: monitoring
spec:
  encryptedData:
    password: AgAPszDpjLbm+fHq8RNShcFs+rb1A0mLP5e9tgsLX37RjXdpuYeuP0kkHywizrrKFgQiRTmZxmOt68vFkIlWnRHuq5ypT75wUj43ziZWvgr/53ySLKlKmTrZaGwyBQDcVRnkTbYGk/noHU/tz7+UjIL1ujClU3c0TXGQlKYFW4PbgnD2dsEiCg+zIE+0mE9CwzQ3IuJfdZuIAOMOLxv9yD0EmbB7nmqV1LfeuXq4vPRW1N0IpoyrEUl3vYn5vI34BSDkiVbkWNgqEWJKUtkZy3pGO7B9WuMmfzWm91lyxtChsDRUS6SlPD3wblrzpgbNdfay166VHdyoUA63cW2kCIUA6ptK9IL6tCjsR3kDpMl3dzBvcwOtO5bDQdm43DiHhnXbJN6xTUuakB9UipY90NLeHMVhKyrUysYwlr4Y3etUo6a5uT/G3wdXjBIvifnqxy1xNDZov8BWBpGjCM4BGJmsih/rBnhsJYStEOo7uHEYPQh/zi8mrq5cpcBKyoD0ueeuk27iGvexxpctPrArEXASWUgV6donPEQB7xmzYMUCcw0aMASuDzkeut7gQTXcTf47PvtFJURvD3avYWAwE57TzGhhOPw43XzuRwV68WyoB1bAdL4xcLN5bBi2JQnqVo44jsChCPsMX9IerfhtLo/BIlIA6BtZeMdw/sf9w09wuDsFVhJ6h63QaKyXOsLSe142K8OBxYFZth9490oSrs6AFlke0g==
    user: AgArMKv+9Irs/O5sdKfnIcm0BF94aogaJZbI5Jz7U3jucQuhUXAJeyo5V2xjavyLTy29ZmjgkmyeyKJ4l6N34tFMUU8MYiidrsC8boIQuEWbv64i+kX63fZLuwpSkNXSlb4DJ6hbd2JCF0m5sORlf4VqSFshjtUtcAritJ0tx7+TvsnW82Tx4Yp6iYjOFmAiA2FvS3IJssN2ey+aDAy+HJ1FSQ5mKv2YREEl9QENP9Amoh6a/w2spsWuD4SSYaczMJIJM6OD2XVKF6aSk54R8/sCIPUed2n+HmGT9j90CQWrCJ5ozwQ4K2rVJ6/mpqnPDqAi9TidFV3V56UEaN46I0DO99imkgcx4itMX86Qct5UuDzZ/nXzxE+vd356QYG+MCaAQhFNlk1W9nqIZS9XexEYoMH3G6+5aUw3OAYafBgiPME54o1kKljiow0fr3lFigO9lqUd25p31bjva+DBwpoeOM0md7XzTnK/vA4TONCS6r0T90C22792bmieUhK+mgIznjy9mnhFGGGweG4kn3KfNiVEfpKQzV5e4MuhaKmCyeuewIh+XyaGxpYwXzDR2XJPhiZlq0IFnFsZTuYY+yx/6b0pme68elAhfg4g8pXC0YBMhyeGee3InMWZTwarcNCInn88XGBk/1/PEo93+dXwGIza91d4n42MmdFQ1SSRYeyekHNB0OvveiyNx0wUrhMwdGDcXA==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: grafana
      namespace: monitoring
