apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: traefik-external
  namespace: networking
spec:
  endpoints:
    - path: /metrics
      targetPort: 9100
  jobLabel: traefik-external
  namespaceSelector:
    matchNames:
      - networking
  selector:
    matchLabels:
      app.kubernetes.io/instance: traefik-external
      app.kubernetes.io/name: traefik
