apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
spec:
  chart:
    spec:
      chart: cert-manager
      sourceRef:
        kind: HelmRepository
        name: jetstack
      version: "1.10.1"
  interval: 1h0m0s
  valuesFrom:
    - kind: ConfigMap
      name: cert-manager-config
