apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
spec:
  chart:
    spec:
      chart: cert-manager
      sourceRef:
        kind: HelmRepository
        name: jetstack
      version: "v1.15.3"
  interval: 1h0m0s
  values:
    installCRDs: true
    extraArgs:
      - --enable-gateway-api
    prometheus:
      enabled: true
      servicemonitor:
        enabled: true
