apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: pki
resources:
  - helmrepository.yaml
  - helmrelease.yaml
configMapGenerator:
  - name: cert-manager-config
    files:
      - values.yaml=values.yaml
configurations:
  - kustomizeconfig.yaml
