apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: duckdns
  namespace: dns
spec:
  encryptedData:
    TOKEN: AgCFvXrX/i6V/1eDg+T2rIydwVxwZC/jKMPEJqk6AxLNIDhfMakSMpJFv/bvmVk27eRgzPfb8TW5Dd+qiWV3/vWrbLTh/iafd9rs2y88XNB0Hefw1HxayOwYyQyNpppyhOHmOOPmj7hTt7eEdA9RbcGD+ftjDiY1zAp+oG4kcux8tHuH/1Rvz4Jh3J7sBk+pM95YIyWabp9Ni+kW9FxEgyYL1tqo2huESM4aNQnpguPt0rpaCP37bhAIG/GIkYr/DeL+SMu5GvqvWCHXP/hG7DyOCRtxw+1SvksRvDTF+tno2YYvtlm8txQ09haPjPJ8oX5cemumoo48f/UL4HalZeKq/vqIpze5A+LpNSEySJ9OikbKHqtUuCU6VwpV86L7k5gl63Ol569hcZxuy+EeRBCXsd0y6MoiQoQIZM3MjAW8Wp1KzkR6W2XSH7F6YZp8LCTSj3X1quWZ8yBL2Y1WJvuf3i9Wt9ddHsrYuPrp7fKljijRwQt6rv4RgllDYlQPngDq3+5IeD251ShlBuhgj+QMmDEJaEy8R3AWu/tnpBMfAFn7Xr8Gg27jd4+/XXRwm4Sxka7u0su0pMMY1nyWmxUwg3fuCdM3HErTj4qIjiiNWEMojnqN+/r7dEVjLbqMkIlKEWSo6+uQ0jEYyriecs1y2yK3Gxk2SX9W1fF/404c+RQBCzWCBtftkT5zOpPqpKmtzdpLtC6FvlBbF3uVDF60buzL7CMW9h39v5Wrc2xP7+PHWMg=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: duckdns
      namespace: dns
