apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: duckdns
spec:
  releaseName: duckdns
  chart:
    spec:
      chart: duckdns
      sourceRef:
        kind: HelmRepository
        name: mmontes
        namespace: flux-system
      version: "0.3.0"
  interval: 5m
  values:
    image:
      repository: linuxserver/duckdns
      pullPolicy: IfNotPresent
      tag: 0168fda3-ls117

    subdomains:
      - mmontes.duckdns.org
      - gotway.duckdns.org

    timezone: Europe/Madrid

    secretRef:
      name: duckdns
