apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dns
resources:
  - duckdns-sealedsecret.yaml
  - duckdns-helmrelease.yaml
  - pihole-sealedsecret.yaml
  - pihole-helmrepository.yaml
  - pihole-helmrelease.yaml
  - pihole-podmonitor.yaml
  - pihole-httproute.yaml
