apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: pihole
spec:
  releaseName: pihole
  chart:
    spec:
      chart: pihole
      sourceRef:
        kind: HelmRepository
        name: pihole
      version: "2.24.0"
  interval: 1h0m0s
  values:
    replicaCount: 3

    podDisruptionBudget:
      enabled: true

    antiaff:
      enabled: true

    serviceDns:
      mixedService: false
      type: LoadBalancer
      externalTrafficPolicy: Cluster
      annotations:
        metallb.universe.tf/loadBalancerIPs: 10.0.0.60
        metallb.universe.tf/allow-shared-ip: pihole-dns-tcp,pihole-dns-udp

    serviceDhcp:
      enabled: false

    serviceWeb:
      enabled: true
      type: LoadBalancer
      externalTrafficPolicy: Cluster
      annotations:
        metallb.universe.tf/loadBalancerIPs: 10.0.0.61
 
    resources:
      requests:
        cpu: 100m
        memory: "100Mi"
      limits:
        memory: "500Mi"

    admin:
      existingSecret: "pihole"
      passwordKey: "password"

    dnsmasq:
      customDnsEntries:
        - address=/pihole.local/10.0.0.61

    monitoring:
      # TODO: podmonitor causes helmrelease to fail after render because it already contains a 'release' key
      podMonitor:
        enabled: false
      sidecar:
        enabled: true
        port: 9617
        image:
          repository: ekofr/pihole-exporter
          tag: v0.4.0
          pullPolicy: IfNotPresent

  postRenderers:
    - kustomize:
        patches:
          - target:
              version: v1
              kind: Service
              name: pihole-web  
            patch: |
              - op: add
                path: /spec/sessionAffinity
                value: ClientIP