apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: pihole
  namespace: dns
spec:
  encryptedData:
    password: AgBEHtStwF0cIrAdbmIMrdJsltAXllumITvT950i6j493QqynGtM3LLkc9XWOUyCpScx2BZUrqYHCjjHWAI0ZPgkr1qUY16T5LGLtfHssAY0QT2wiTgVQFpx2WBVLe2ozGvikJu3kSkhctn4POonwXfFyuSrUGBA1e58lrjxP9jdWxq85t6Rmie48pWAmiDJMM+dDuhgFHaEg8Lx70rADNTmPTg/JFPs2qXl/xauU5X5aE3soC4Y5XWn94kcUfyDL17QIc+qIFP6k89T7WHJKVHwmvOJEOxrtkRyTScrowVtpSoohjXbvpHJ1s5MMsV5IHB1n3NYmh7lPkptLSHkLf2l2zBosRXHV2n3C2PhNtULyPJDaEGu3JJM5cIdcE1Y2++GDrSRl1mYeGW6zfREImtVHO0as6Y/K9j6z9ewrzHBaPZBmZVbgZ5/7oo8YjScPPa3+xQpYpATmGKzjfudbYYMLAG1C2CgsEuWhKU1v+MSa78lsDMYgPFtugulhcRe47gdiTMvqDh8jULeLU+tE+8ohVkW8+sC91InWr1EDwFOIeEpCjpCj2ZL+I2Qe22NCB4Jtt0SDa2i54dfBvXiOMJhrAwG2usScOUUGUeVFdBer5GEz3VuXYrL0V7Z8+I/DYFMpupL/0lSEO6BQlRvQajdmMhiSXotg04MAG5nV5G44YvQp5uRDF4KPuwebiOvEXkC5r9odDr1Fw6YYIu1h7iFQyRSaQ==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: pihole
      namespace: dns

