apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: pihole
spec:
  parentRefs:
    - name: traefik-internal
      namespace: networking
  hostnames:
    - "pihole.mmontes-internal.duckdns.org"
  rules:
    - backendRefs:
        - name: pihole-web
          port: 80
