apiVersion: volsync.backube/v1alpha1
kind: ReplicationDestination
metadata:
  name: photoprism-prometheus
spec:
  trigger:
    manual: prometheus-2
  restic:
    repository: restic-prometheus
    destinationPVC: data-prometheus-kube-prometheus-stack-prometheus-0
    # Direct method is required to inherit tolerations from Pod.
    # TODO: use Snapshot after migrating to homelab-v2  
    copyMethod: Direct
    moverResources:
      requests:
        cpu: 1
        memory: 300Mi
      limits:
        memory: 4Gi
    cacheCapacity: 10Gi
    cacheStorageClassName: topolvm
    cacheAccessModes:
      - ReadWriteOnce
    customCA:
      secretName: homelab-bundle
      key: ca.crt
