apiVersion: volsync.backube/v1alpha1
kind: ReplicationDestination
metadata:
  name: prometheus
spec:
  trigger:
    manual: prometheus-1
  restic:
    repository: restic-prometheus
    destinationPVC: data-prometheus-kube-prometheus-stack-prometheus-0
    copyMethod: Snapshot
    moverResources:
      requests:
        cpu: 1
        memory: 300Mi
      limits:
        memory: 4Gi
    cacheCapacity: 10Gi
    cacheStorageClassName: topolvm
    cacheAccessModes:
      - ReadWriteOnce
    customCA:
      secretName: homelab-bundle
      key: ca.crt
