apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: prometheus
spec:
  sourcePVC: data-prometheus-kube-prometheus-stack-prometheus-0
  trigger:
    # schedule: "0 2 * * *"
    manual: prometheus-2
  restic:
    repository: restic-prometheus
    retain:
      daily: 7
    pruneIntervalDays: 14
    unlock: prometheus-1
    # Direct method is required to inherit tolerations from Pod.
    # TODO: use Clone after migrating to homelab-v2  
    copyMethod: Direct
    moverResources:
      requests:
        cpu: 1
        memory: 300Mi
      limits:
        memory: 4Gi
    moverAffinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: node.mmontes.io/type
                  operator: In
                  values:
                    - compute-large
    cacheCapacity: 10Gi
    cacheStorageClassName: topolvm
    cacheAccessModes:
      - ReadWriteOnce
    customCA:
      secretName: homelab-bundle
      key: ca.crt
