apiVersion: "cilium.io/v2"
kind: CiliumClusterwideNetworkPolicy
metadata:
  name: cluster-egress
  namespace: networking
spec:
  endpointSelector: {}
  egress:
    - toEntities:
        - all
  egressDeny:
    - toCIDRSet:
        - cidr: 10.0.0.0/24
          except:
            - 10.0.0.10/32
            - 10.0.0.11/32
            - 10.0.0.12/32
            - 10.0.0.13/32
            - 10.0.0.14/32
