apiVersion: "cilium.io/v2"
kind: CiliumClusterwideNetworkPolicy
metadata:
  name: cluster-egress
  namespace: networking
spec:
  description: "Deny access to host network for all namespaces except networking and kube-system"
  endpointSelector:
    matchExpressions:
    - key: "k8s:io.kubernetes.pod.namespace"
      operator: "NotIn"
      values:
      - networking
      - kube-system
  egress:
  - toEntities:
    - host
    toPorts:
    - ports:
      - port: "1"
        protocol: ANY
