apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: homelab-tls
spec:
  secretName: homelab-tls
  duration: 26280h # 3y
  renewBefore: 720h # 30d
  isCA: true
  usages:
    - "digital signature"
    - "key encipherment"
    - "cert sign"
  commonName: homelab
  issuerRef:
    name: selfsigned
    kind: ClusterIssuer