apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: topolvm
spec:
  chart:
    spec:
      chart: topolvm
      sourceRef:
        kind: HelmRepository
        name: topolvm
      version: "15.5.6"
  interval: 1h0m0s
  values:
    lvmd:
      managed: true
      deviceClasses:
        - name: nvme
          volume-group: topolvm
          default: true
          type: thin
          spare-gb: 30
          thin-pool:
            name: "pool0"
            overprovision-ratio: 1.5
      initContainers:
        - name: lvm-init
          image: ubuntu:24.04
          securityContext:
            privileged: true
          command:
            - /bin/bash
            - -c
          args:
            - |
              set -euo pipefail

              apt update && apt install -y lvm2
              cat <<EOF > /etc/lvm/lvm.conf
              devices {
                  obtain_device_list_from_udev = 0
                  use_devicesfile = 0
                  issue_discards = 0
              }
              activation {
                  udev_sync = 0
                  udev_rules = 0
                  use_lvmetad = 0
              }
              EOF

              DEVICE="${DEVICE:-/dev/sdb}"
              VG_NAME="${VG_NAME:-topolvm}"
              THIN_POOL_NAME="${THIN_POOL_NAME:-pool0}"
              THIN_POOL_SIZE="${THIN_POOL_SIZE:-95%FREE}"

              echo "Waiting for $DEVICE..."
              while [ ! -b "$DEVICE" ]; do sleep 1; done

              if ! pvs "$DEVICE" >/dev/null 2>&1; then
                echo "Creating physical volume on $DEVICE"
                pvcreate "$DEVICE"
              else
                echo "Physical volume already exists on $DEVICE"
              fi
              pvdisplay "$DEVICE"

              if ! vgs "$VG_NAME" >/dev/null 2>&1; then
                echo "Creating volume group $VG_NAME"
                vgcreate "$VG_NAME" "$DEVICE"
              else
                echo "Volume group $VG_NAME already exists"
              fi
              vgdisplay "$VG_NAME"

              if ! lvs "$VG_NAME/$THIN_POOL_NAME" >/dev/null 2>&1; then
                echo "Creating thin pool $THIN_POOL_NAME in $VG_NAME"
                lvcreate -T -n "$THIN_POOL_NAME" -L "$THIN_POOL_SIZE" "$VG_NAME"
              else
                echo "Thin pool $THIN_POOL_NAME already exists in $VG_NAME"
              fi
              lvdisplay "$VG_NAME/$THIN_POOL_NAME"

              echo "LVM init complete"
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          volumeMounts:
          - name: devices-dir 
            mountPath: /dev
      tolerations:
        - effect: NoSchedule
          key: node.mmontes.io/type
          value: compute-large
        - effect: NoSchedule
          key: node.mmontes.io/type
          value: compute-xlarge
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: node.mmontes.io/type
                    operator: In
                    values:
                      - compute-large
                      - compute-xlarge
      metrics:
        enabled: true
      prometheus:
        podMonitor:
          enabled: true
    node:
      lvmdEmbedded: false
      tolerations:
        - effect: NoSchedule
          key: node.mmontes.io/type
          value: compute-large
        - effect: NoSchedule
          key: node.mmontes.io/type
          value: compute-xlarge
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: node.mmontes.io/type
                    operator: In
                    values:
                      - compute-large
                      - compute-xlarge
      metrics:
        enabled: true
      prometheus:
        podMonitor:
          enabled: true
    controller:
      # TODO: bump to 2 replicas when homelab-v2 fully migrated
      replicaCount: 1
      prometheus:
        podMonitor:
          enabled: true
    storageClasses:
      - name: topolvm
        storageClass:
          fsType: xfs
          reclaimPolicy: Delete
          isDefaultClass: false
          volumeBindingMode: WaitForFirstConsumer
          allowVolumeExpansion: true
          additionalParameters:
            topolvm.io/device-class: "nvme"
    snapshot:
      enabled: true