apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: topolvm
spec:
  chart:
    spec:
      chart: topolvm
      sourceRef:
        kind: HelmRepository
        name: topolvm
      version: "15.5.6"
  interval: 1h0m0s
  values:
    lvmd:
      managed: true
      deviceClasses:
        - name: nvme
          volume-group: topolvm
          default: true
          type: thin
          spare-gb: 30
          thin-pool:
            name: "pool0"
            overprovision-ratio: 1.5
      initContainers:
        - name: lvm-init
          image: ghcr.io/mmontes11/lvm-init:v0.1.0
          securityContext:
            privileged: true
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          volumeMounts:
          - name: devices-dir 
            mountPath: /dev
      tolerations:
        - effect: NoSchedule
          key: node.mmontes.io/type
          value: compute-large
        - effect: NoSchedule
          key: node.mmontes.io/type
          value: compute-xlarge
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: node.mmontes.io/type
                    operator: In
                    values:
                      - compute-large
                      - compute-xlarge
      metrics:
        enabled: true
      prometheus:
        podMonitor:
          enabled: true
    node:
      lvmdEmbedded: false
      tolerations:
        - effect: NoSchedule
          key: node.mmontes.io/type
          value: compute-large
        - effect: NoSchedule
          key: node.mmontes.io/type
          value: compute-xlarge
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: node.mmontes.io/type
                    operator: In
                    values:
                      - compute-large
                      - compute-xlarge
      metrics:
        enabled: true
      prometheus:
        podMonitor:
          enabled: true
    controller:
      replicaCount: 2
      tolerations:
        - effect: NoSchedule
          key: node.mmontes.io/type
          value: compute-large
        - effect: NoSchedule
          key: node.mmontes.io/type
          value: compute-xlarge
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app.kubernetes.io/component
                    operator: In
                    values:
                      - controller
                  - key: app.kubernetes.io/name
                    operator: In
                    values:
                      - topolvm
              topologyKey: kubernetes.io/hostname
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: node.mmontes.io/type
                    operator: In
                    values:
                      - compute-large
                      - compute-xlarge
      prometheus:
        podMonitor:
          enabled: true
    storageClasses:
      - name: topolvm
        storageClass:
          fsType: xfs
          reclaimPolicy: Delete
          isDefaultClass: false
          volumeBindingMode: WaitForFirstConsumer
          allowVolumeExpansion: true
          additionalParameters:
            topolvm.io/device-class: "nvme"
    snapshot:
      enabled: true
    resources:
      topolvm_node:
        requests:
          memory: 100Mi
          cpu: 100m
        limits:
          memory: 500Mi
          cpu: 500m
      csi_registrar:
        requests:
          cpu: "25m"
          memory: "10Mi"
        limits:
          cpu: "200m"
          memory: "200Mi"
      liveness_probe:
        requests:
          cpu: "25m"
          memory: "10Mi"
        limits:
          cpu: "200m"
          memory: "200Mi"
      topolvm_controller:
        requests:
          memory: "50Mi"
          cpu: "50m"
        limits:
          memory: "200Mi"
          cpu: "200m"
      csi_provisioner:
        requests:
          memory: "50Mi"
          cpu: "50m"
        limits:
          memory: "200Mi"
          cpu: "200m"
      csi_resizer:
        requests:
          memory: "50Mi"
          cpu: "50m"
        limits:
          memory: "200Mi"
          cpu: "200m"
      csi_snapshotter:
        requests:
          memory: "50Mi"
          cpu: "50m"
        limits:
          memory: "200Mi"
          cpu: "200m"
      lvmd:
        requests:
          memory: 100Mi
          cpu: 100m
        limits:
          memory: 500Mi
          cpu: 500m