apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: storage
resources:
  - external-snapshotter-deployment.yaml
  - external-snapshotter-rbac.yaml
  - webhook-certificate.yaml
  - webhook-configuration.yaml
  - webhook-deployment.yaml
  - webhook-rbac.yaml
  - webhook-service.yaml