apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: snapshot-validation-webhook-cert
spec:
  commonName: snapshot-validation-service.storage.svc
  dnsNames:
  - snapshot-validation-service.storage.svc.cluster.local
  - snapshot-validation-service.storage.svc
  - snapshot-validation-service.storage
  - snapshot-validation-service
  issuerRef:
    kind: ClusterIssuer
    name: homelab
  revisionHistoryLimit: 3
  secretName: snapshot-validation-webhook-cert
