apiVersion: apps/v1
kind: Deployment
metadata:
  name: snapshot-validation-deployment
  labels:
    app.kubernetes.io/name: snapshot-validation
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: snapshot-validation
  template:
    metadata:
      labels:
        app.kubernetes.io/name: snapshot-validation
    spec:
      serviceAccountName: snapshot-webhook
      containers:
      - name: snapshot-validation
        image: registry.k8s.io/sig-storage/snapshot-validation-webhook:v8.0.1
        imagePullPolicy: IfNotPresent
        args:
        - '--tls-cert-file=/etc/snapshot-validation-webhook/certs/tls.crt'
        - '--tls-private-key-file=/etc/snapshot-validation-webhook/certs/tls.key'
        - '--enable-volume-group-snapshot-webhook'
        ports:
        - containerPort: 443
        volumeMounts:
          - name: snapshot-validation-webhook-cert
            mountPath: /etc/snapshot-validation-webhook/certs
            readOnly: true
      volumes:
        - name: snapshot-validation-webhook-cert
          secret:
            secretName: snapshot-validation-webhook-cert