apiVersion: v1
kind: Service
metadata:
  name: snapshot-validation-service
spec:
  selector:
    app.kubernetes.io/name: snapshot-validation
  ports:
    - protocol: TCP
      port: 443
      targetPort: 443