apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: rook
spec:
  releaseName: rook
  chart:
    spec:
      chart: rook-ceph
      sourceRef:
        kind: HelmRepository
        name: rook
      version: "v1.16.5"
  interval: 1h0m0s
  values:
    crds:
      enabled: false

    rbacAggregate:
      enableOBCs: true

    resources:
      requests:
        cpu: 1
        memory: 300Mi
      limits:
        memory: 300Mi

    csi:      
      enableRbdDriver: true
      enableCephfsDriver: true

      enableRBDSnapshotter: true
      enableCephfsSnapshotter: true
      enableVolumeGroupSnapshot: true
  
      rbdFSGroupPolicy: "File"
      cephFSFSGroupPolicy: "File"

      provisionerReplicas: 2
      provisionerTolerations:
        - effect: NoSchedule
          key: node.mmontes.io/storage
      provisionerNodeAffinity: node.mmontes.io/type=storage
        
      serviceMonitor:
        enabled: true
    
    monitoring:
      enabled: true