apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: rook
spec:
  releaseName: rook
  chart:
    spec:
      chart: rook-ceph
      sourceRef:
        kind: HelmRepository
        name: rook
      version: "v1.14.9"
  interval: 1h0m0s
  values:
    rbacAggregate:
      enableOBCs: true
    csi:
      enableRbdDriver: true
      enableCephfsDriver: false

      enableRBDSnapshotter: false
      enableCephfsSnapshotter: false
      enableNFSSnapshotter: false

      provisionerReplicas: 1

      nfs:
        enabled: false
      serviceMonitor:
        enabled: true
    monitoring:
      enabled: true