apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: rook
spec:
  releaseName: rook
  chart:
    spec:
      chart: rook-ceph
      sourceRef:
        kind: HelmRepository
        name: rook
      version: "v1.15.1"
  interval: 1h0m0s
  values:
    crds:
      enabled: false

    rbacAggregate:
      enableOBCs: true

    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        memory: 512Mi

    csi:      
      enableRbdDriver: true
      enableRBDSnapshotter: true
      rbdFSGroupPolicy: "File"

      enableCephfsDriver: true
      enableCephfsSnapshotter: true
      cephFSFSGroupPolicy: "File"

      provisionerReplicas: 2
      provisionerTolerations:
        - effect: NoSchedule
          key: node.mmontes.io/storage

      pluginTolerations:
        - effect: NoSchedule
          key: node.mmontes.io/storage
        
      serviceMonitor:
        enabled: true
    
    monitoring:
      enabled: true