apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: rook
spec:
  releaseName: rook
  chart:
    spec:
      chart: rook-ceph
      sourceRef:
        kind: HelmRepository
        name: rook
      version: "v1.14.9"
  interval: 1h0m0s
  values:
    resources:
      limits:
        memory: 512Mi
      requests:
        cpu: 100m
        memory: 128Mi
    rbacAggregate:
      enableOBCs: true
    csi:
      provisionerReplicas: 1
      enableRbdDriver: true
      enableRBDSnapshotter: false
      enableCephfsDriver: false
      enableCephfsSnapshotter: false
      enableNFSSnapshotter: false
      nfs:
        enabled: false
      serviceMonitor:
        enabled: true
    monitoring:
      enabled: true