apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: rook
spec:
  releaseName: rook
  chart:
    spec:
      chart: rook-ceph
      sourceRef:
        kind: HelmRepository
        name: rook
      version: "v1.18.2"
  interval: 1h0m0s
  values:
    crds:
      enabled: false

    rbacAggregate:
      enableOBCs: true

    resources:
      requests:
        cpu: 1
        memory: 300Mi
      limits:
        memory: 300Mi

    ceph-csi-operator:
      nameOverride: ceph-csi
      fullnameOverride: ceph-csi
      controllerManager:
        manager:
          env:
            csiServiceAccountPrefix: "ceph-csi-"

    csi:
      rookUseCsiOperator: true

      enableRbdDriver: true
      enableCephfsDriver: true

      enableRBDSnapshotter: true
      enableCephfsSnapshotter: true
      enableVolumeGroupSnapshot: true
  
      rbdFSGroupPolicy: "File"
      cephFSFSGroupPolicy: "File"

      provisionerReplicas: 2
      provisionerTolerations:
        - effect: NoSchedule
          key: node.mmontes.io/type
          value: storage
      provisionerNodeAffinity: node.mmontes.io/type=storage
        
      pluginTolerations:
        - effect: NoSchedule
          key: node.mmontes.io/type
          value: compute-large
        - effect: NoSchedule
          key: node.mmontes.io/type
          value: compute-xlarge

      cephcsi:
        repository: quay.io/cephcsi/cephcsi
        tag: v3.15.0

      registrar:
        repository: registry.k8s.io/sig-storage/csi-node-driver-registrar
        tag: v2.14.0

      provisioner:
        repository: registry.k8s.io/sig-storage/csi-provisioner
        tag: v5.3.0

      snapshotter:
        repository: registry.k8s.io/sig-storage/csi-snapshotter
        tag: v8.3.0

      attacher:
        repository: registry.k8s.io/sig-storage/csi-attacher
        tag: v4.9.0

      resizer:
        repository: registry.k8s.io/sig-storage/csi-resizer
        tag: v1.14.0

      csiRBDProvisionerResource: |
        - name : csi-provisioner
          resource:
            requests:
              cpu: 50m
              memory: 100Mi
            limits:
              memory: 100Mi
        - name : csi-resizer
          resource:
            requests:
              cpu: 50m
              memory: 100Mi
            limits:
              memory: 100Mi
        - name : csi-attacher
          resource:
            requests:
              cpu: 50m
              memory: 100Mi
            limits:
              memory: 100Mi
        - name : csi-snapshotter
          resource:
            requests:
              cpu: 50m
              memory: 100Mi
            limits:
              memory: 100Mi
        - name : csi-rbdplugin
          resource:
            requests:
              cpu: 50m
              memory: 100Mi
            limits:
              memory: 100Mi
        - name : csi-omap-generator
          resource:
            requests:
              cpu: 50m
              memory: 100Mi
            limits:
              memory: 100Mi
        - name : liveness-prometheus
          resource:
            requests:
              cpu: 50m
              memory: 100Mi
            limits:
              memory: 100Mi

      csiRBDPluginResource: |
        - name : driver-registrar
          resource:
            requests:
              cpu: 50m
              memory: 100Mi
            limits:
              memory: 100Mi
        - name : csi-rbdplugin
          resource:
            requests:
              cpu: 50m
              memory: 100Mi
            limits:
              memory: 100Mi
        - name : liveness-prometheus
          resource:
            requests:
              cpu: 50m
              memory: 100Mi
            limits:
              memory: 100Mi

      csiCephFSProvisionerResource: |
        - name : csi-provisioner
          resource:
            requests:
              cpu: 50m
              memory: 100Mi
            limits:
              memory: 100Mi
        - name : csi-resizer
          resource:
            requests:
              cpu: 50m
              memory: 100Mi
            limits:
              memory: 100Mi
        - name : csi-attacher
          resource:
            requests:
              cpu: 50m
              memory: 100Mi
            limits:
              memory: 100Mi
        - name : csi-snapshotter
          resource:
            requests:
              cpu: 50m
              memory: 100Mi
            limits:
              memory: 100Mi
        - name : csi-cephfsplugin
          resource:
            requests:
              cpu: 50m
              memory: 100Mi
            limits:
              memory: 100Mi
        - name : liveness-prometheus
          resource:
            requests:
              cpu: 50m
              memory: 100Mi
            limits:
              memory: 100Mi

      csiCephFSPluginResource: |
        - name : driver-registrar
          resource:
            requests:
              cpu: 50m
              memory: 100Mi
            limits:
              memory: 100Mi
        - name : csi-cephfsplugin
          resource:
            requests:
              cpu: 50m
              memory: 100Mi
            limits:
              memory: 100Mi
        - name : liveness-prometheus
          resource:
            requests:
              cpu: 50m
              memory: 100Mi
            limits:
              memory: 100Mi

      serviceMonitor:
        enabled: true
    
    monitoring:
      enabled: true