apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: github-explorer
spec:
  releaseName: github-explorer
  targetNamespace: github-explorer
  chart:
    spec:
      chart: ./charts/tenant
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  interval: 5m
  values:
    repo:
      url: ssh://git@github.com/mmontes11/k8s-github-explorer
      branch: main
      path: ./clusters/production
      secretName: flux-system
