apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: github-explorer
spec:
  releaseName: github-explorer
  targetNamespace: github-explorer
  chart:
    spec:
      chart: tenant
      sourceRef:
        kind: HelmRepository
        name: mmontes
        namespace: flux-system
      version: "0.1.0"
  interval: 5m
  values:
    repo:
      url: ssh://git@github.com/mmontes11/k8s-github-explorer
      branch: main
      path: ./clusters/homelab
      secretName: flux-system
