apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: synology-csi
spec:
  releaseName: synology-csi
  chart:
    spec:
      chart: synology-csi
      sourceRef:
        kind: HelmRepository
        name: synology-csi
      version: "0.10.1"
  interval: 1h0m0s
  values:
    fullnameOverride: synology
    clientInfoSecret:
      create: false
      name: client-info
    images:
      attacher:
        image: registry.k8s.io/sig-storage/csi-attacher
        pullPolicy: IfNotPresent
        tag: v4.8.1
      nodeDriverRegistrar:
        image: registry.k8s.io/sig-storage/csi-node-driver-registrar
        pullPolicy: IfNotPresent
        tag: v2.13.0
      plugin:
        image: synology/synology-csi
        pullPolicy: IfNotPresent
      provisioner:
        image: registry.k8s.io/sig-storage/csi-provisioner
        pullPolicy: IfNotPresent
        tag: v5.2.0
      resizer:
        image: registry.k8s.io/sig-storage/csi-resizer
        pullPolicy: IfNotPresent
        tag: v1.13.2
      snapshotter:
        image: registry.k8s.io/sig-storage/csi-snapshotter
        pullPolicy: IfNotPresent
        tag: v8.2.0
    storageClasses:
      iscsi:
        disabled: false
        isDefault: false
        reclaimPolicy: Delete
        parameters:
          dsm: "10.0.0.50"
          fsType: btrfs
          location: /volume1
          protocol: iscsi
      iscsi-retain:
        disabled: false
        isDefault: false
        reclaimPolicy: Retain
        parameters:
          dsm: "10.0.0.50"
          fsType: btrfs
          location: /volume1
          protocol: iscsi
      iscsi-delete: null
      nfs-delete: null
      nfs-retain: null
      smb-delete: null
      smb-retain: null
    volumeSnapshotClasses:
      iscsi:
        disabled: false
        isDefault: false
        deletionPolicy: Delete
        parameters:
          description: "Kubernetes CSI"
          is_locked: "false"
      iscsi-retain:
        disabled: false
        isDefault: false
        deletionPolicy: Retain
        parameters:
          description: "Kubernetes CSI"
          is_locked: "false"
      delete: null
      retain: null
  postRenderers:
    - kustomize:
        patches:
          - target:
              kind: ClusterRole
              name: synology-snapshotter
            patch: |
              - op: add
                path: /rules/-
                value:
                  apiGroups:
                    - snapshot.storage.k8s.io
                  resources:
                    - volumesnapshotcontents/status
                  verbs:
                    - patch
