apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: synology-csi
spec:
  releaseName: synology-csi
  chart:
    spec:
      chart: synology-csi
      sourceRef:
        kind: HelmRepository
        name: synology-csi
      version: "0.9.10"
  interval: 1h0m0s
  values:
    fullnameOverride: synology-csi
    clientInfoSecret:
      create: false
      name: client-info
    storageClasses:
      delete: null
      retain: null
      storage:
        disabled: false
        isDefault: false
        reclaimPolicy: Retain
        parameters:
          dsm: "10.0.0.50"
          fsType: ext4
          location: /volume1
          protocol: iscsi
          type: thin