apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: volsync
spec:
  chart:
    spec:
      chart: volsync
      sourceRef:
        kind: HelmRepository
        name: volsync
      version: "v0.10.0"
  interval: 1h0m0s
  values:
    replicaCount: 2

    image:
      repository: bitnami/volsync
    rclone:
      repository: bitnami/volsync
    restic:
      repository: bitnami/volsync
    rsync:
      repository: bitnami/volsync
    rsync-tls:
      repository: bitnami/volsync
    syncthing:
      repository: bitnami/volsync

    manageCRDs: true

    metrics:
      disableAuth: true