apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: volsync
spec:
  chart:
    spec:
      chart: volsync
      sourceRef:
        kind: HelmRepository
        name: volsync
      version: "v0.10.0"
  interval: 1h0m0s
  values:
    replicaCount: 2

    image:
      repository: ghcr.io/mmontes11/volsync
      tag: v0.10.0
    rsync-tls:
      repository: ghcr.io/mmontes11/volsync
      tag: v0.10.0

    manageCRDs: true

    metrics:
      disableAuth: true